### ISSUE TITLE
Remove Super Stream Provider or a way to hide

### ISSUE THREAD

**Issue by intellimediatv** [stantanasi/streamflix#100]
### Summary

Unsure if you are unaware Super Stream provider does not have a large current and old library of content it also promotes adult content xxx not sure if this is the direction you planned to take the app in. Also will u provide users with a "setting" feature so they can select their own personal options

### Please confirm the following

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.

**Comment by stantanasi** [comment]
Oh okay didn't know about that, it's was just an easy provider to add so I just implement it.
I will remove the adult contents!

**Comment by stantanasi** [comment]
I intend to add a settings page but it's so much work that I postpone it every time

**Comment by stantanasi** [comment]
**Adult contents removed on [Release 1.6.2](https://github.com/stantanasi/streamflix/releases/latest)**
