### ISSUE TITLE
Cast titles have infinite duplicates when you scroll (sorastream)

### ISSUE THREAD

**Issue by oathzed** [stantanasi/streamflix#101]
### Description

When you scroll down from a cast members filmography, it will just keep duplicating them and scroll forever

### Reproduction steps

reference video: https://imgur.com/a/sIgn3s2

### App version

latest

### Operating system

shield android tv

### Please confirm the following

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] If related to a provider, I have checked the site and it works, but not the app.

**Comment by stantanasi** [comment]
SoraStream ?

**Comment by oathzed** [comment]
> SoraStream ?

sorry yes, sorastream

**Comment by stantanasi** [comment]
**Fixed on [Release 1.6.3](https://github.com/stantanasi/streamflix/releases/latest)**
