### ISSUE TITLE
Marking watched on another list doesn't remove progress bar on that list until restart of app

### ISSUE THREAD

**Issue by oathzed** [stantanasi/streamflix#102]
### Description

if you have progress on a movie, and you remove that progress by marking it watched, or removing it from the continue watched section, in that list it wont remove the progress bar until you restart the app

### Reproduction steps

video for reference: https://imgur.com/a/gNmwoOA

### App version

latest

### Operating system

shield android tv

### Please confirm the following

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] If related to a provider, I have checked the site and it works, but not the app.

**Comment by stantanasi** [comment]
**Fixed on [Release 1.6.3](https://github.com/stantanasi/streamflix/releases/latest)**
