### ISSUE TITLE
Infinite scroll on horizontal lists (sorastream)

### ISSUE THREAD

**Issue by oathzed** [stantanasi/streamflix#103]
### Summary

now that you're using TheMovieDB in sorastream as a metadata provider, is it possible we can get infinite scroll on horizontal lists (currently it's at 20 items, just like sflix, but sflix has that limitation) 

video for reference: https://imgur.com/a/owmTbvp

### Please confirm the following

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.

**Comment by stantanasi** [comment]
Don't think I will implement it because it will ask too much work and change in my code, sorry
I could increase the number of items, if you want?

**Comment by oathzed** [comment]
> Don't think I will implement it because it will ask too much work and change in my code, sorry I could increase the number of items, if you want?

Ahh ok fair enough. Maybe if it was atleast 100 items per list that would be fine?

**Comment by stantanasi** [comment]
Okay, I'll see what I can do

**Comment by stantanasi** [comment]
**Increasing number of items available on Release 1.6.7**

**Comment by oathzed** [comment]
> **Increasing number of items available on Release 1.6.7**

Much better thanks :). Only issue I've noticed is HBO still doesn't have movies and it only has 20 items in the list still, all the others have 40

**Comment by stantanasi** [comment]
> Much better thanks :). Only issue I've noticed is HBO still doesn't have movies and it only has 20 items in the list still, all the others have 40

Thanks, I hadn't noticed
I just did some tests and I can correct this by adding movies, but I notice that HBO doesn't have many movies and especially good movies. So I'm wondering if I still add the movies or I only increase the number of TV shows.

To give an example, here are the first movies I retrieve:
Gia - 1998
The Many Saints of Newark - 2021
My Big Fat Greek Wedding 2 - 2016

**Comment by oathzed** [comment]
> > Much better thanks :). Only issue I've noticed is HBO still doesn't have movies and it only has 20 items in the list still, all the others have 40
> 
> Thanks, I hadn't noticed I just did some tests and I can correct this by adding movies, but I notice that HBO doesn't have many movies and especially good movies. So I'm wondering if I still add the movies or I only increase the number of TV shows.
> 
> To give an example, here are the first movies I retrieve: Gia - 1998 The Many Saints of Newark - 2021 My Big Fat Greek Wedding 2 - 2016

Ahh ok got yeh, I guess they are mainly a tv show platform. Don't they have documentary movies? If not then yeh just increase tv shows I guess

**Comment by stantanasi** [comment]
> Don't they have documentary movies?

I'm not really sure but I thinks I will just increase the number of TV shows, and if people still want to watch documentary/movies from HBO then they will search for it

**Comment by oathzed** [comment]
> > Don't they have documentary movies?
> 
> I'm not really sure but I thinks I will just increase the number of TV shows, and if people still want to watch documentary/movies from HBO then they will search for it

Sounds good, thanks

**Comment by stantanasi** [comment]
**Done on Release 1.6.8**

**Comment by oathzed** [comment]
> **Done on Release 1.6.8**

Thanks!
