### ISSUE TITLE
Add movies to horizontal streaming services lists (sorastream)

### ISSUE THREAD

**Issue by oathzed** [stantanasi/streamflix#104]
### Summary

I know this is happening in the original sorastream addon as well, but since you're using themovieDB as the metadata, are you able to add movies to these lists?

video for reference: https://imgur.com/a/lyeAVz9

### Please confirm the following

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.

**Comment by stantanasi** [comment]
Hey sorry for the delay!
Yes, I can add anything, do you have something in mind?

**Comment by oathzed** [comment]
> Hey sorry for the delay! Yes, I can add anything, do you have something in mind?

Hey no worries! Lists like "popular movies on x streaming service" trending movies" stuff like that that's popular right now

**Comment by stantanasi** [comment]
Currently, in the homepage, there is a lot of list, do you think it's necessary to have all of them? 
I say this because in my opinion no one should go to some list, I think about: Airing Today TV shows, Hulu, Paramount, Peacock, Top rated movies, Top rated TV shows, Korean Shows, Airing Today anime, On the air anime
So should I remove them (less requests on the homepage) or do I let all/some of them?

**Comment by oathzed** [comment]
> Currently, in the homepage, there is a lot of list, do you think it's necessary to have all of them? I say this because in my opinion no one should go to some list, I think about: Airing Today TV shows, Hulu, Paramount, Peacock, Top rated movies, Top rated TV shows, Korean Shows, Airing Today anime, On the air anime So should I remove them (less requests on the homepage) or do I let all/some of them?

Yeh I hear yeh. I'd say these can all go in my opinion, Hulu sometimes has some decent stuff:

Airing today tv shows
Paramount+
Peacock
Top rated tv shows
Top rated movies
Korean shows
Airing today anime
On the air anime
Anime
Anime movies

**Comment by oathzed** [comment]
> > Currently, in the homepage, there is a lot of list, do you think it's necessary to have all of them? I say this because in my opinion no one should go to some list, I think about: Airing Today TV shows, Hulu, Paramount, Peacock, Top rated movies, Top rated TV shows, Korean Shows, Airing Today anime, On the air anime So should I remove them (less requests on the homepage) or do I let all/some of them?
> 
> Yeh I hear yeh. I'd say these can all go in my opinion, Hulu sometimes has some decent stuff. And there are anime apps that are utilized specifically for anime:
> 
> Airing today tv shows Paramount+ Peacock Top rated tv shows Top rated movies Korean shows Airing today anime On the air anime Anime Anime movies

**Comment by stantanasi** [comment]
**Available on Release 1.6.7**
