### ISSUE TITLE
Sort casts titles by most recent (sorastream)

### ISSUE THREAD

**Issue by oathzed** [stantanasi/streamflix#105]
### Summary

Can you sort them so we can see the most recent thing they've been in? I think currently its maybe by most popular? it would be useful to see so we can be like oh they're in a new movie, I want to watch that :P.

photo for reference: 
![photo_4909145515250265203_y](https://github.com/stantanasi/streamflix/assets/52545913/69490267-f039-4478-ba1c-d9f0270920d5)

### Please confirm the following

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.

**Comment by stantanasi** [comment]
**Available on Release 1.6.6**

**Comment by az51blog** [comment]
Well done thank you everything is perfect now 
Will if we could add a Data backup option to sync across our devices it will be amazing 🤩

**Comment by stantanasi** [comment]
> Will if we could add a Data backup option to sync across our devices it will be amazing 🤩

I see what you mean but it would ask too much work, I will have to create an API, store the data inside a network database and create accounts for each user.
Maybe at some point but not soon
