### ISSUE TITLE
Continue watching section, have it open the TV info page when you press back

### ISSUE THREAD

**Issue by oathzed** [stantanasi/streamflix#108]
### Summary

If you watch an episode from the continue watching section, and you finish it, when you press back, it takes you back to the home page. Instead it should take you back to that tv shows page, so if you want to watch the next episode, all you gotta do is press the "watch" button. 

Currently it takes a lot more time, cause you have to re-find that tv show and open it up to watch the next episode.

Another thing that would be nice, but not sure if it's currently possible without a service like trakt. Keeping whatever episode you have next to watch in your continue watching list. If you're all caught up, but then a new episode comes out it will also pop up in your continue watching list.

Video for reference: https://imgur.com/a/0GEUluO

### Please confirm the following

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.

**Comment by oathzed** [comment]
Updated the issue with this as well (not sure if it's possible with the current setup though?):

"Another thing that would be nice, but not sure if it's currently possible without a service like trakt. Keeping whatever episode you have next to watch in your continue watching list. If you're all caught up, but then a new episode comes out it will also pop up in your continue watching list."

**Comment by stantanasi** [comment]
> Another thing that would be nice, but not sure if it's currently possible without a service like trakt. Keeping whatever episode you have next to watch in your continue watching list. If you're all caught up, but then a new episode comes out it will also pop up in your continue watching list.

This would be possible but it will require too many requests when launching the application, which will cause the application to slow down.

**Comment by oathzed** [comment]
> > Another thing that would be nice, but not sure if it's currently possible without a service like trakt. Keeping whatever episode you have next to watch in your continue watching list. If you're all caught up, but then a new episode comes out it will also pop up in your continue watching list.
> 
> This would be possible but it will require too many requests when launching the application, which will cause the application to slow down.

Makes sense

**Comment by oathzed** [comment]
> > Another thing that would be nice, but not sure if it's currently possible without a service like trakt. Keeping whatever episode you have next to watch in your continue watching list. If you're all caught up, but then a new episode comes out it will also pop up in your continue watching list.
> 
> This would be possible but it will require too many requests when launching the application, which will cause the application to slow down.

Makes sense

**Comment by stantanasi** [comment]
**Available on [Release 1.6.3](https://github.com/stantanasi/streamflix/releases/latest)**
