### ISSUE TITLE
Show episodes of the series on the same detail page

### ISSUE THREAD

**Issue by Ajtak** [stantanasi/streamflix#11]
I think it would be useful to show the parts directly on the detail screen, under the seasons. It would be nice to modify the seasons button to a different type of selection, and display the episodes directly on the same page.

There is also a list of episodes on the web sflix.to on one page at the same time with details.

**Comment by stantanasi** [comment]
The app was initially like this, it displayed all episodes directly on TV show details page. You can find this functionnality until commit 05622fb2b4071287df9c16cc84a9eee2a3f32e11.

However, displaying all episodes of a TV show on the details page means loading them all at once, which takes a lot of time.
Assuming you want to watch One Piece, the app will need to load all 1000 episodes for you to watch a single episode. It might take a few minutes to load them all.

The sflix.to website displays the episodes on the detail page but only those of the first season. To view the other episodes, you still have to select the season.

**Comment by Ajtak** [comment]
I think having the season selection on one page is a more acceptable solution. Something like spinner/dropdown/select could be cool. That would be a similar style to the web.

Loading one season might not be a problem.
