### ISSUE TITLE
Search button on on-screen keyboard not working

### ISSUE THREAD

**Issue by 91ramguy** [stantanasi/streamflix#110]
### Description

When I search anything in the search bar, instead of searching when I hit Search on the on-screen keyboard, it exits the search bar and highlights a random category below

### Reproduction steps

1. Open search in menu. 2. Type in search bar with remote using on-screen keyboard. 3. Hit search button on on-screen keyboard

### Operating system

Android TV 10

### Please confirm the following

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] If related to a provider, I have checked the site and it works, but not the app.

**Comment by stantanasi** [comment]
Uhh it's really weird, I never had/heard of something like this. I'll try to look into it.

**Comment by 91ramguy** [comment]
If it helps, I'm running this custom build of Android TV https://konstakang.com/devices/rpi4/LineageOS17.1-ATV/ on a Raspberry PI 4B, I doubt that's part of the issue though

**Comment by stantanasi** [comment]
Okay thanks, I don't have a computer currently but as soon as I buy a new one I'll look into it

**Comment by stantanasi** [comment]
Could you try if it works with new version 1.6.7 please
