### ISSUE TITLE
Nothing loads

### ISSUE THREAD

**Issue by GH0STREAP3R** [stantanasi/streamflix#111]
### Description

Using SFlix and trying to play anything I get a popup saying "Unable to resolve host "keys4.fun": No address associated with hostname." Tried using multiple devices and also with VPN enabled and disabled.

### Reproduction steps

1. Click on media
2. Click on episode/movie

### App version

1.6.2

### Operating system

Android 14

### Please confirm the following

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] If related to a provider, I have checked the site and it works, but not the app.

**Comment by stantanasi** [comment]
Use an other provider for now (I recommend Sorastream)

**Comment by GH0STREAP3R** [comment]
> Use an other provider for now (I recommend Sorastream)

I was also getting errors last night trying both Sorastream and Superstream, seem to be working now tho.

**Comment by morrens** [comment]
I get exactly the same error Unable to resolve host "keys4.fun when i use sflix provider
i use an android mi box

**Comment by stantanasi** [comment]
**SFlix and TMDb (ex SoraStream) fixed on [Release 1.6.5](https://github.com/stantanasi/streamflix/releases/latest)**
