### ISSUE TITLE
Implement subtitle options in Sorastream provider

### ISSUE THREAD

**Issue by theblvckdragon** [stantanasi/streamflix#112]
### Summary

Would it be possible to have subtitles in the sorastream provider? Amazing work! 

### Please confirm the following

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.

**Comment by stantanasi** [comment]
**Available on [Release 1.6.3](https://github.com/stantanasi/streamflix/releases/latest)**
