### ISSUE TITLE
Auto Select from sources

### ISSUE THREAD

**Issue by raycekar** [stantanasi/streamflix#114]
### Summary

Add the ability to when selecting a show, the app will search through all available stream sites instead of needing the user to try one source, if it doesn't work, then moves to the next.

### Please confirm the following

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.

**Comment by stantanasi** [comment]
**Available on [Release 1.6.3](https://github.com/stantanasi/streamflix/releases/latest)**

**Comment by mbegaa** [comment]
My install is prompting no extractors found error
