### ISSUE TITLE
Failing to connect to host in Sorastream provider

### ISSUE THREAD

**Issue by intellimediatv** [stantanasi/streamflix#115]
### Description

Failing to connect to host 127.0.0.1:80 for Sorastream nothing is working

### Reproduction steps

Open app click on all movies same eror message

### App version

Version 1.6.2 version

### Operating system

Android OS 13

### Please confirm the following

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] If related to a provider, I have checked the site and it works, but not the app.

**Comment by ob5cur3** [comment]
@stantanasi Did you get a chance to look at it? If you could give me a pointer on where should I look at for this specific issue I shall try to fix and create a PR.

**Comment by stantanasi** [comment]
Found a temporary solution, sometimes it works sometimes it don't 🤷‍♂️

**Comment by stantanasi** [comment]
**Temporary fixed on [Release 1.6.3](https://github.com/stantanasi/streamflix/releases/latest)**
Sometimes it works, sometimes it don't (e.g. "Can't retrieve source")

**Comment by intellimediatv** [comment]
Yea now seeing and getting on Soratream provider  HTTP 404 error and "cant retrieve source"....Also SuperStream not even opening anymore

**Comment by Brennasummers** [comment]
Same here.

**Comment by DjSpartaKe254** [comment]
I don't understand how there's an update yet it doesn't fix anything...

**Comment by oathzed** [comment]
> I don't understand how there's an update yet it doesn't fix anything...

There's actually a lot of stuff that was fixed. Go use another app for the time being if it doesn't work for you, there's plenty of them that will get you by for now..

**Comment by intellimediatv** [comment]
There have been many changes in the newest 1.6.3 but the main function of the app does not work the developer is aware and researching more meanwhile it is a fact there are other apps to have as alternatives until all bugs are fixed in future updates

**Comment by ob5cur3** [comment]
@oathzed  Do you have other recommended apps?

**Comment by DjSpartaKe254** [comment]
> @oathzed  Do you have other recommended apps? 

I actually have some...just temporary before streamflix is fixed. I just dont know if this is the right place to share them.
