### ISSUE TITLE
Version 1.6.3 reverts back to mobile version

### ISSUE THREAD

**Issue by intellimediatv** [stantanasi/streamflix#116]
### Description

Version 1.6.3 reverts back to mobile version from 1.6.2-tv upgrade

### Reproduction steps

Update from 1.6.2-tv version reverts to mobile layout upon completing update

### App version

Version 1.6.3

### Operating system

Android 9.0

### Please confirm the following

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] If related to a provider, I have checked the site and it works, but not the app.

**Comment by Jeanblake26** [comment]
yeah it is back on mobile version please bring back TV BOX VERSION OR ANDROID TV VERSION

**Comment by stantanasi** [comment]
Could you check if this [APK version](https://github.com/stantanasi/streamflix/releases/download/v1.6.3/app-debug.apk) works?

**Comment by intellimediatv** [comment]
Will check later this afternoon / evening

**Comment by intellimediatv** [comment]
That debug apk does not change into TV interface still showing mobile and still unable to find content

**Comment by stantanasi** [comment]
**Possibility to change app UI layout on [Release 1.6.4](https://github.com/stantanasi/streamflix/releases/latest)**
