### ISSUE TITLE
app crashes after starting

### ISSUE THREAD

**Issue by Parasgaming122** [stantanasi/streamflix#117]
### Description

when i click on the app it shows the ui for 1 sec then crashes i installed it on my tv

### Reproduction steps

click on the app

### App version

latesy

### Operating system

android 13 tv box

### Please confirm the following

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] If related to a provider, I have checked the site and it works, but not the app.

**Comment by stantanasi** [comment]
Could you reinstall it and tell me if you still have this problem

**Comment by Parasgaming122** [comment]
> Could you reinstall it and tell me if you still have this problem

Yeah I tried it didn't work

**Comment by Parasgaming122** [comment]
https://github.com/stantanasi/streamflix/issues/123#issue-2345431167 and I see the latest release has the same problem

**Comment by stantanasi** [comment]
**You can now download the Streamflix app for TV only (if your device isn't correctly recognized as a TV or mobile) on [Release 1.7.2](https://github.com/stantanasi/streamflix/releases/latest)**
