### ISSUE TITLE
The app is prompting no extractors found error

### ISSUE THREAD

**Issue by mbegaa** [stantanasi/streamflix#118]
### Description

My install is prompting no extractors found error when playing any file

### Reproduction steps

My install is prompting no extractors found error when playing any file

### Operating system

Android 12.0

### Please confirm the following

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] If related to a provider, I have checked the site and it works, but not the app.

**Comment by stantanasi** [comment]
**SFlix and TMDb (ex SoraStream) fixed on [Release 1.6.5](https://github.com/stantanasi/streamflix/releases/latest)**

**Comment by 1gby** [comment]
This is a issue for me on the lastest release same error message
