### ISSUE TITLE
Everything i play says cant retrieve source

### ISSUE THREAD

**Issue by hassan-waris** [stantanasi/streamflix#119]
### Description

Hi everyone I'm trying to play a few shows I've missed and wanted to catch up ok but everything I play keeps saying that it can't retrieve from source? Am I missing something or do I have to pay for something?

Thank you

### Reproduction steps

Any thing I play when I'm in sora stream says cant retrieve source
![Screenshot_20240425_154131_Streamflix](https://github.com/stantanasi/streamflix/assets/29949941/4fe0a9ee-b20b-4df5-a0c0-1ffd01399335)

### Operating system

Android 14.0 one ui 6.1

### Please confirm the following

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] If related to a provider, I have checked the site and it works, but not the app.

**Comment by Jeanblake26** [comment]
i dont know what is goin on on streamflix this is the best app since 2022-23 but now in 2024 it totally can not be used

**Comment by stantanasi** [comment]
Maybe because I don't have as much time as before. I'm in vacation till June so I will not work on it.
If you want to fix it, you're more than welcome!

**Comment by oathzed** [comment]
> Maybe because I don't have as much time as before. I'm in vacation till June so I will not work on it. If you want to fix it, you're more than welcome!

Enjoy your vacation man! Some of us appreciate all your hard work and don't make duplicates of the same issue 😂. Thanks again for making such a polished app!

**Comment by stantanasi** [comment]
**SFlix and TMDb (ex SoraStream) fixed on [Release 1.6.5](https://github.com/stantanasi/streamflix/releases/latest)**
