### ISSUE TITLE
app stopped working

### ISSUE THREAD

**Issue by ajimal173** [stantanasi/streamflix#12]
dear admin,

from y/day app stopped working both 1.1.0 and 1.2.0 pls take a look n fix

> im using mi box 4k android version 9.0.
> sir actually 1.1.0 app not open at first attempt after 5 to 6 attempt then only app opening the dashboard
> 
> now latest version 1.2.0 app open but at first asking 2 option which server to open "all movies" or "sflix" tab
> sflix content not loading still loader loading content not opening,
> all movies also not working showing error like no handshake
> 
> note:
> still 1.1.0 working but we need to open app atleast 4 to 5 click then only app opening
> 
> pls take a look n fix i really unable to watch movies from sflix app

**Comment by stantanasi** [comment]
I just tested the app right now, and it works fine for me.
Could you provide more details on what is not working and where?

PS: The homepage has been taking a long time to load lately, I need to look into it.

**Comment by stantanasi** [comment]
This issue was closed because it has been stalled for too many days without activity. Please open a new issue if you believe you are encountering a related problem.
