### ISSUE TITLE
content  not playing

### ISSUE THREAD

**Issue by ajimal173** [stantanasi/streamflix#122]
### Description

after the update 1.6.3 movies n series or anime section not playing after u upgrade to "[app-debug.apk](https://github.com/stantanasi/streamflix/releases/download/v1.6.3/app-debug.apk)" also content not working pls fix

### Reproduction steps

1. movies not playing
2. series not playing
3. anime not playing
4. error showing cant retrieve to play source

### App version

app-debug.apk

### Please confirm the following

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] If related to a provider, I have checked the site and it works, but not the app.

**Comment by stantanasi** [comment]
**SFlix and TMDb (ex SoraStream) fixed on [Release 1.6.5](https://github.com/stantanasi/streamflix/releases/latest)**
