### ISSUE TITLE
URL to provider keeps changing

### ISSUE THREAD

**Issue by fahedayub** [stantanasi/streamflix#124]
### Summary

In my country, the website sfllix.to opens, but your app does not display anything when I try to access SFLIX. It seems the links to the websites might be different in your code. Is there a way for me to modify the link to match the webpage that opens in my country?

### Please confirm the following

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.

**Comment by DarkCrypt** [comment]
SFlix is working.

**Comment by fahedayub** [comment]
DrakCrypt, thanks,I checked it now, it is working.
