### ISSUE TITLE
Tmdb provider is down

### ISSUE THREAD

**Issue by intellimediatv** [stantanasi/streamflix#125]
### Description

Server does not play content error message from java
![Screenshot_20240613_124550_Streamflix](https://github.com/stantanasi/streamflix/assets/109838034/5ca97e3c-a5b6-4642-a8b8-1a01bb4909e8)

### Provider

Tmdb

### Reproduction steps

Select TMDB provider then select movie java script error

### Operating system

Nvidia Shield Android TV OS version 11.0

### Logs

```bash
Java error message content does not play
```

### Please confirm the following

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] If related to a provider, I have checked the site and it works, but not the app.

**Comment by popcorn2024ok** [comment]
![20240615_000542](https://github.com/stantanasi/streamflix/assets/165403113/47b1b618-a5b5-4d63-b02e-0a0259b0fc56)

I get this error in the tmdb provider in the series and movies the tmdb provider is down is there a solution for this problem and error

HTTP  404

**Comment by Doctor2023** [comment]
> ![20240615_000542](https://private-user-images.githubusercontent.com/165403113/339913362-47b1b618-a5b5-4d63-b02e-0a0259b0fc56.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg0MDM0MDYsIm5iZiI6MTcxODQwMzEwNiwicGF0aCI6Ii8xNjU0MDMxMTMvMzM5OTEzMzYyLTQ3YjFiNjE4LWE1YjUtNGQ2My1iMDJlLTBhMDI1OWIwZmM1Ni5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjE0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYxNFQyMjExNDZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05ZTBjOTU3ZmI0NWQ2MjgyNjVjODE3MzZhMzM2YTE5ZDg1YTUxM2RlZjQwMzc5YzgzZjBkODkxMzI1MzM4YmZkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.cPPMPkCS32VfPeoNjTqKE5hMRp3nYc5bAxyflsPmiiI)
> 
> I get this error in the tmdb provider in the series and movies the tmdb provider is down is there a solution for this problem and error
> 
> HTTP 404

I also get that HTTP 404 message in the tmdb provider in streamflix

**Comment by intellimediatv** [comment]
The tmdb provider has been fixed

**Comment by popcorn2024ok** [comment]
https://github.com/stantanasi/streamflix/assets/165403113/293e8a84-5e84-4e57-a9c5-b3ac46759691

What appears in the video is the problem of the tmdb provider with animes and movies and series

**Comment by intellimediatv** [comment]
I wouldnt use this app for anime there are dedicated apps for that....you can also switch to h!anime provider in the app and SFLIX provider

**Comment by popcorn2024ok** [comment]
> I wouldnt use this app for anime there are dedicated apps for that....you can also switch to h!anime provider in the app and SFLIX provider

So the tmdb provider has been fixed, there are no more problems and errors, but there will be an update for the tmdb provider when there will be improvements also for streamflix and other providers for streamflix

**Comment by DarkCrypt** [comment]
Working for me.

**Comment by popcorn2024ok** [comment]
I get this HTTP 404 error message in some movies and series This is a bug I think there is a solution With this HTTP 404 message that appears when playing movies and series the video

**Comment by intellimediatv** [comment]
The 404 error will come to movies and tv shows not already released or with  no server access available

**Comment by popcorn2024ok** [comment]
> The 404 error will come to movies and tv shows not already released or with no server access available

But there is a solution with that, with the problem with the series and movies I have tried with a series called Powerpuff Girls Z and Hi Hi Puffy AmiYumi
with the episodes and
the HTTP 404 message appears

**Comment by intellimediatv** [comment]
Because the app is just a scraper it wil not have every single tv series, movie or anime content hence the 404 error message....consider other apps or even KODi for ur anime

**Comment by popcorn2024ok** [comment]
> Because the app is just a scraper it wil not have every single tv series, movie or anime content hence the 404 error message....consider other apps or even KODi for ur anime

So the problem is the animes in the tmdb provider, not the movies and series. I wanted to see some Hollywood movies and series, some are not available, others are available, movies and series and they should add more providers on streamflix

**Comment by intellimediatv** [comment]
Have u really looked at the app there are other providers in StreamFlix smh SFLIX is a provider for movies and tv shows as well and its working

**Comment by DarkCrypt** [comment]
> Because the app is just a scraper it wil not have every single tv series, movie or anime content hence the 404 error message

Exactly. Good luck finding a source that has everything you search for.

> So the problem is the animes in the tmdb provider, not the movies and series. I wanted to see some Hollywood movies and series, some are not available, others are available, movies and series and they should add more providers on streamflix

This TMDb provider is a multisource provider and there's only 1 provider available at this time. Stantanasi hasn't had time (he's building this by himself) to implement more extractors for the rest of the providers. When he is able to do so there will be more content available.
