### ISSUE TITLE
TMDB provider links

### ISSUE THREAD

**Issue by anon45-ui** [stantanasi/streamflix#126]
### Summary

Needs like 2 more backup links not just one it only has vidsc.to needs more servers than that 

### Please confirm the following

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.

**Comment by DarkCrypt** [comment]
Duplicate of #98.

**Comment by popcorn2024ok** [comment]
![IMG_1007](https://github.com/stantanasi/streamflix/assets/165403113/f7b3b458-04f0-44b8-a4cb-48377919c6a6)

I can't play some movies and series I get this error in the tmdb provider in the streamflix app
 
 no extractors  found

**Comment by stantanasi** [comment]
Duplicate of #98
