### ISSUE TITLE
HTTP 404 issues

### ISSUE THREAD

**Issue by anon45-ui** [stantanasi/streamflix#129]
### Description

Some movies keeps saying http 404 which is very annoying needs to be fixed

### Provider

The Movie DB

### Reproduction steps

Some movies keeps saying http 404 which is very annoying needs to be fixed

### Operating system

Android 13

### Logs

```bash
Some movies keeps saying http 404 which is very annoying needs to be fixed
```

### Please confirm the following

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] If related to a provider, I have checked the site and it works, but not the app.

**Comment by stantanasi** [comment]
What movies?

**Comment by anon45-ui** [comment]
Long list mostly the 1980's and 70's movies and 2024 movies that recently came out thats the only bad thing about that provider needs improvements
the invitation (1984)
Python II  (2002)
Boa vs Python (2004) 
Boa (1999) 
Maybe even more but can't name all of them thats the only bad thing when vidsrc.to is the only server in that provider

**Comment by popcorn2024ok** [comment]
The same thing happens to me I get that problem with tmdb provider HTTP 404  @stantanasi @anon45-ui

**Comment by anon45-ui** [comment]
It really needs to be fixed

**Comment by popcorn2024ok** [comment]
> It really needs to be fixed

I also think the same as you

**Comment by stantanasi** [comment]
When the movie show a 404 error, it means that the movie is not available. For example, really old and not famous movie or too recent movies.
I could and will add more video source, but sometimes the movie can just be impossible to watch on streaming

**Comment by popcorn2024ok** [comment]
> When the movie show a 404 error, it means that the movie is not available. For example, really old and not famous movie or too recent movies. I could and will add more video source, but sometimes the movie can just be impossible to watch on streaming

Hello friend can you add more Streamflix movie and series providers that are in Spanish and English, it would be great if you added more movie and series providers that have more content as Streamflix add-ons and also free movie and series websites for 2024 We are in July

**Comment by stantanasi** [comment]
Closing this because I can't do anything about the 404 error, **the movie is not available**

Will implement more extractors (servers): #98
