### ISSUE TITLE
TMDB provider down again

### ISSUE THREAD

**Issue by intellimediatv** [stantanasi/streamflix#130]
### Description

"No Extractors Found" error on all movies and tv series in TMDB provoder

### Provider

TMDB 

### Reproduction steps

Click on any tv series or movie to "play"
Error message no extractors found

### Operating system

Nvidia Shield Android TV OS version 11.0

### Please confirm the following

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] If related to a provider, I have checked the site and it works, but not the app.

**Comment by az51blog** [comment]
Same problem here 
I began to love the app and depend on it all the way.
I Wish the author fix the problem soon 
And thx very much For his great effort I didn't imagine I would have an application that beat Netflix and the prime video etc. all in one and with all the subtitles

**Comment by az51blog** [comment]
> Just switch to SFlix provider in the app that still works give the dev some time hopefully he will fix TMDB provider as well

Unfortunately Sflix doesn't support all subtitles as TMDB but thanks I try to do so

**Comment by anon45-ui** [comment]
> > Just switch to SFlix provider in the app that still works give the dev some time hopefully he will fix TMDB provider as well
> 
> Unfortunately Sflix doesn't support all subtitles as TMDB but thanks I try to do so

That's true and Anymovies is limited when it comes to movies

**Comment by stantanasi** [comment]
**Fixed on Release 1.6.6**

**Comment by az51blog** [comment]
Thank you very much for your effort everything now is works like a charm 
Love and greeting from Egypt
