### ISSUE TITLE
Please add the font-size of 125% and 150%

### ISSUE THREAD

**Issue by Benlee1129** [stantanasi/streamflix#131]
### Summary

Font-size in type of 200% is too large, but default (100%) is too small. The font size of 125% is well decorated.

### Please confirm the following

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.

**Comment by stantanasi** [comment]
**Available on Release 1.6.6**

**Comment by Benlee1129** [comment]
Yes, it works fine now on v. 1.6.6.
Thanks for your efforts.

**Comment by az51blog** [comment]
Everything works perfectly thank you very much
