### ISSUE TITLE
Retrieve subtitles from OpenSubtitles

### ISSUE THREAD

**Issue by Benlee1129** [stantanasi/streamflix#132]
### Summary

Currently leading commercial video providers support full list of subtitles from A to V. Would you please provide subtitles such as that from opensubstitle added automatically for later videos?
Or whether the module like Google translate is embedded in the app for translating subtitles to specific language. 

### Please confirm the following

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.

**Comment by stantanasi** [comment]
Currently the subtitles are added automatically from the video itself, I don't have any influence on the subtitles added

**Comment by stantanasi** [comment]
Okay will do!!

**Comment by stantanasi** [comment]
**Available on Release 1.6.9**
