### ISSUE TITLE
Is the option for external player set on the settings?

### ISSUE THREAD

**Issue by Benlee1129** [stantanasi/streamflix#133]
### Summary

Would you please have a set of option in the menu of internal player to call external player such as mx player or vlc for playing the content?

### Please confirm the following

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.

**Comment by stantanasi** [comment]
Will see what I can do!
Do you have an example of external player, for me to test it?

**Comment by Benlee1129** [comment]
Mx player or vlc player are multifunctional and free.

Lory-Stan TANASI ***@***.***> 於 2024年7月12日 週五 21:01 寫道：

**Comment by stantanasi** [comment]
For documentation:
[https://mx.j2inter.com/api](https://mx.j2inter.com/api)
[https://wiki.videolan.org/Android_Player_Intents](https://wiki.videolan.org/Android_Player_Intents)

**Comment by stantanasi** [comment]
**Available on Release 1.6.10**

![Screenshot_20240730-113711_Streamflix-1](https://github.com/user-attachments/assets/0c2a9d12-c1a2-467d-9e68-90a07e0ca74d)
