### ISSUE TITLE
Favourites, history or progress

### ISSUE THREAD

**Issue by Axanderism** [stantanasi/streamflix#136]
### Summary

A quick way to access shows being watched from the home screen, rather than searching at every app start.  This could be in the form of a favourites list, a watch history, or a Progress list from Trakt. Once the app starts to the home screen, it shouldn't take more than 2 clicks to continue watching a show! 

### Please confirm the following

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.

**Comment by stantanasi** [comment]
Already implemented it, when you arrive on a movie or TV show you can favorite it with a button near the "Watch" button
