### ISSUE TITLE
App Crash

### ISSUE THREAD

**Issue by yessabrar** [stantanasi/streamflix#137]
### Description

Firstly I loved the app, it smoothly worked in my phone but whenever i go to start Streamflix in my ANDROID TV..it crashes for all the time! i was so excited to play movies in my tv but it won't happend :')

### Provider

not even got the time to chose before it got crashed

### Reproduction steps

(Android tv)
1. Open the app
2. Got Crashed 

### Operating system

Android tv v7

### Please confirm the following

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] If related to a provider, I have checked the site and it works, but not the app.

**Comment by stantanasi** [comment]
Try resetting app data by going Settings > Apps > Streamflix > Storage > Clear data
Or by reinstalling the app

**Comment by yessabrar** [comment]
Still Crash and Says "Streamflix keeps stop running" Any other app u have or any suggestion?

**Comment by rijaslive** [comment]
> Try resetting app data by going Settings > Apps > Streamflix > Storage > Clear data
> Or by reinstalling the app

I updated to the latest version and tried your solution many times, but it is not working.

The same version works properly on my mobile device without any issues.

**Comment by stantanasi** [comment]
**You can now download the Streamflix app for TV only (if your device isn't correctly recognized as a TV or mobile) on [Release 1.7.2](https://github.com/stantanasi/streamflix/releases/latest)**
