### ISSUE TITLE
Aspect ratio option in settings

### ISSUE THREAD

**Issue by Uvdon** [stantanasi/streamflix#138]
### Summary

It would be nice to add zoom option for videos. Please and thank you. Nice player by the way and thanks for not adding stupid gestures

### Please confirm the following

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.

**Comment by stantanasi** [comment]
I see what you mean but I don't understand in what way you will use it.
In my case, if I zoom when watching I will miss some corner on the movie so I don't understand why you want it?

**Comment by oathzed** [comment]
> I see what you mean but I don't understand in what way you will use it. In my case, if I zoom when watching I will miss some corner on the movie so I don't understand why you want it?

Yeh I also don't understand why people use those resize features.. they just want it to be full screen but at the loss of parts of the video, they either don't understand that or don't care and just want full screen lol.

**Comment by Uvdon** [comment]
Hi sorry for the late reply. So, i totally understand why you would think changing the aspect ratio is useless but there are some videos that are too small in size and it's very annoying to have big black bars on the sides (very annoying if your like me who has hdhd). Anyways its your app and in the end i respect your decision.

Also, if your reading this, can you add sorastream

**Comment by stantanasi** [comment]
> Hi sorry for the late reply. So, i totally understand why you would think changing the aspect ratio is useless but there are some videos that are too small in size and it's very annoying to have big black bars on the sides (very annoying if your like me who has hdhd). Anyways its your app and in the end i respect your decision.

I will try to add it, but it could take some time before I add it, I will have to know how to it.

> Also, if your reading this, can you add sorastream

SoraStream has been renamed TMDb (The Movie DB) !!

**Comment by elvin1119** [comment]
Awesome app. Thank you.
A resize option for movies would be great 👍

**Comment by stantanasi** [comment]
**Available on Release 1.6.10**

![Screenshot_20240730-113711_Streamflix-2](https://github.com/user-attachments/assets/8b7cbf14-bf1c-490e-97d1-27652214cd14)
