### ISSUE TITLE
App crash on all provider (TV LAYOUT)

### ISSUE THREAD

**Issue by github-jl14** [stantanasi/streamflix#141]
### Description

I somehow did a alternative approach to the #139 issue i opened via using MATVT to click the TV layout option (coz Auto doesn't make it tv. i tried restarting the app)

App crashes 

### Provider

ALL PROVIDERS

### Reproduction steps

1. Launch app
2. Select tv layout
3. Select any provider
4. App crashes

Next time you open the app, it just crashes after the start screen.

### Operating system

MXQ Pro 4K TVBOX (Fake Android 12: its Android 7.1 [based on the api level])

### Please confirm the following

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] If related to a provider, I have checked the site and it works, but not the app.

**Comment by stantanasi** [comment]
**You can now download the Streamflix app for TV only (if your device isn't correctly recognized as a TV or mobile) on [Release 1.7.2](https://github.com/stantanasi/streamflix/releases/latest)**
