### ISSUE TITLE
Many new bugs in version 1.6.8 Not Playable

### ISSUE THREAD

**Issue by intellimediatv** [stantanasi/streamflix#144]
### Description

no content is playing in version 1.6.8 
TMDB provider not working

### Provider

TMDB 

### Reproduction steps

click on movie or tv show nothing playable

### Operating system

Nvidia Shield Android TV OS version 11.0

### Please confirm the following

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] If related to a provider, I have checked the site and it works, but not the app.

**Comment by popcorn2024ok** [comment]
![2024_07_21_11 42 45](https://github.com/user-attachments/assets/e2e79f83-07a1-4cbb-aeb4-bdf719fed830)
![2024_07_21_11 39 51](https://github.com/user-attachments/assets/c6f3f780-0533-40b4-a264-89dfea8dfc4d)
![2024_07_21_11 40 45](https://github.com/user-attachments/assets/d1886448-679f-4aaf-ae46-91b4bcf11311)
![2024_07_21_11 41 58](https://github.com/user-attachments/assets/8ab00c84-e3cf-4a0d-bfb7-312aa61684f8)

I get these problems in streamflix version 1.6.8 sonc4vproblems in the videos servers

**Comment by stantanasi** [comment]
This errors occurs because the app can't retrieve video source from server.
For some movies/TV shows, it works (Example: My Spy the Eternal City, The Garfield Movie), but for others it's not possible to retrieve the video.

Before the server Vidsrc.to worked, and it had a lots of movies and TV shows, but they changed their encryption method #140 
So for now, some movies/TV shows will works, and some will not.

**Comment by LedveLedve** [comment]
There is a great streaming site 2flix.to, seems related to anix.to, which is a source for amarullz's AnimeTV, so far the best anime apk I've seen. Suggest you to look into it as an alternative for tmdb.

**Comment by stantanasi** [comment]
**Vidsrc.to server fixed on Release 1.6.9**

**Comment by stantanasi** [comment]
> There is a great streaming site 2flix.to, seems related to anix.to, which is a source for amarullz's AnimeTV, so far the best anime apk I've seen. Suggest you to look into it as an alternative for tmdb.

Will look into it, but the errors are not caused by the streaming site but because the retrieving of the video source is encrypted and they change this encryption regularly
