### ISSUE TITLE
SFlix errors

### ISSUE THREAD

**Issue by github-jl14** [stantanasi/streamflix#148]
### Description

---

All servers throw errors. Upstream and Vidstream has the same errors

Mixdrop says no extractors

somewhat same as the reported TMDb provider issues on #144

---

### Screenshots:

---

**Upcloud & Vidstream**

![Screenshot_20240724-161111~2](https://github.com/user-attachments/assets/8aa192e1-2a91-4ca4-a163-3f98f4704497)

_* just replace the Upcloud on the error Vidstream and that's the other provider's error_
_** don't mind the other play button. i screen recorded but i cant upload so i ss'ed it instead_ 

---

**Mixdrop**

![Screenshot_20240724-161524~2](https://github.com/user-attachments/assets/aa8c2d4b-457b-47be-8980-51d94dddb5f6)

---

### Provider

SFlix

### Reproduction steps

try to play any series/movie on the SFlix provider

### Operating system

Android phone, Android 11 (R)

### Please confirm the following

- [ ] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] If related to a provider, I have checked the site and it works, but not the app.

**Comment by fikrydev** [comment]
I experience the same problem, I check the provider and sflix is working fine

**Comment by intellimediatv** [comment]
try to watch the 1990 Movie Presumed Innocent in SFLIX provider none of the servers are working properly
![20240726_133203](https://github.com/user-attachments/assets/4c7cc6a0-0547-439b-8026-ccb24fdbc8ed)

**Comment by stantanasi** [comment]
**Fixed on Release 1.6.10**
