### ISSUE TITLE
Would opensubstitle be added to the track?

### ISSUE THREAD

**Issue by Benlee1129** [stantanasi/streamflix#151]
### Summary

Opensubstitles work on video and let the video reconnected instead of the subtitle added into the track directly. Would you please refine the situation?

### Please confirm the following

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.

**Comment by stantanasi** [comment]
I don't understand what you mean

**Comment by Benlee1129** [comment]
I am sorry!

Subtitle or audio has its own track for video player. While I select English subtitle the content of subtitle would be load into the track but not reconnected the video with integrity of the subtitle.

In the Streamflix, while I load the subtitle the video would stop and reconnect and sometimes the player was crashed.

**Comment by stantanasi** [comment]
If I understand your problem correctly, it is that when you select a subtitle from OpenSubtitles, the player restarts
This is normal, it is not possible to add external subtitles when the video is already launched without restarting the player.

On the other hand, you say that the player crashes when it restarts, which is very strange. Can you give me more information about this (the movie that crashes, the subtitle that crashes...)

**Comment by Benlee1129** [comment]
Thanks for your interpretation in detail.

Some videos were crashed (time frame kept whole) since the vidsrc.to server detected an interruption from opensubstitle loading.

**Comment by stantanasi** [comment]
Will check what I can do

**Comment by Benlee1129** [comment]
I check the video, streaming form vidcloud or upcloud server, capable of being loaded with opensubstitle and being played on external player.

**Comment by PhantomZ-star** [comment]
I have had this problem since for quite awhile. When I select a subtitle track from opensubtitle, the player restarts and doesn't start the video. 
Here's an example video:

https://github.com/user-attachments/assets/477053bf-aa4c-4a1c-82c9-c8c41c67e80b

**Comment by stantanasi** [comment]
**Fixed on Release 1.6.11**
