### ISSUE TITLE
Serienstream (German) streaming wont work.

### ISSUE THREAD

**Issue by JekGG** [stantanasi/streamflix#152]
### Description

If i want to start a video, the loading screen starts and stops directly. Only if i choose Video-Player for playing, it works.

![WhatsApp Image 2024-07-30 at 16 35 01(1)](https://github.com/user-attachments/assets/440fa50d-ce09-4d4a-848a-b229aa48c9df)
![WhatsApp Image 2024-07-30 at 16 35 01](https://github.com/user-attachments/assets/b06ccc60-04e5-4134-8023-382b0f3db319)

### Provider

Serienstream (German)

### Reproduction steps

1. Go to Serienstrem provider
2. Search any Series
3. Play

### Operating system

Android 13

### Please confirm the following

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] If related to a provider, I have checked the site and it works, but not the app.

**Comment by JekGG** [comment]
![WhatsApp Image 2024-07-30 at 16 39 46](https://github.com/user-attachments/assets/e4f9d181-c29a-4609-aa65-7fbf7c9c62d5)

**Comment by stantanasi** [comment]
Will look into it, thx
