### ISSUE TITLE
any movies, sflix, superstream,tmdb are not working

### ISSUE THREAD

**Issue by rajaaaaaaax** [stantanasi/streamflix#155]
### Summary

any movies, sflix, superstream,tmdb are not working

and i want to use this code also

### Please confirm the following

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.

**Comment by popcorn2024ok** [comment]
What improvements and changes will there be in this year 2024 in August friend with Streamflix app

**Comment by stantanasi** [comment]
Not a feature, it's a bug
And duplicate of multiple other issues
