### ISSUE TITLE
please add video slide option

### ISSUE THREAD

**Issue by Subhash407** [stantanasi/streamflix#156]
### Summary

not able to skip or cut video ... 

### Please confirm the following

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.

**Comment by Uvdon** [comment]
The most useless feature along with brightness and volume control lmfao

**Comment by oathzed** [comment]
> The most useless feature along with brightness and volume control lmfao

Yeh the app really doesn't need all this bloat for people that don't know how to use their phone

**Comment by Uvdon** [comment]
Agreed
