### ISSUE TITLE
Selector not show until I press down

### ISSUE THREAD

**Issue by oathzed** [stantanasi/streamflix#161]
### Description

Test on tv show: "Lady in the lake" S01E02

If you add that to your continue watching section, and then long press it, it will have nothing selected, I believe it is because there are two lines of titles because this doesn't happen on short titled episodes.

Video showing what happens:
https://imgur.com/a/WhwHtW9

### Provider

N/A

### Reproduction steps

1. Watch part of episode 2 of lady in the lake
2. Go to continue watching
3. Long press episode
4. See result

### Operating system

Shield tv

### Please confirm the following

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] If related to a provider, I have checked the site and it works, but not the app.

**Comment by stantanasi** [comment]
Thanks man, I will look into it and fix it
Sorry for the delay, I was busy a lot this last few weeks

**Comment by oathzed** [comment]
> Thanks man, I will look into it and fix it Sorry for the delay, I was busy a lot this last few weeks

No problem man, take your time. Hope you're doing good

**Comment by stantanasi** [comment]
Yeah I'm doing great ❤️, was just doing some personal things, other projects...

**Comment by oathzed** [comment]
> Yeah I'm doing great ❤️, was just doing some personal things, other projects...

Good to hear 😊❤️

**Comment by stantanasi** [comment]
**Fixed normally on Release 1.6.11**
