### ISSUE TITLE
Redundant episode title

### ISSUE THREAD

**Issue by oathzed** [stantanasi/streamflix#162]
### Description

![PXL_20240901_204534781 MP~2](https://github.com/user-attachments/assets/78b3533f-fa51-46ba-b07b-cf3b97cfae6d)

Refer to picture, doesn't seem necessary to have the episode title shown twice.

### Provider

N/A

### Reproduction steps

1. Long press and episode in continue watching section
2. See redundant title, shown twice.

### Operating system

Shield tv

### Please confirm the following

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] If related to a provider, I have checked the site and it works, but not the app.

**Comment by stantanasi** [comment]
**Fixed on Release 1.6.11**
