### ISSUE TITLE
SFlix's servers display "HTTP 404" error

### ISSUE THREAD

**Issue by XED07** [stantanasi/streamflix#164]
### Description

I notice today, that any server or provider unable to load any movies and tv shows. It shows error like HTTP 404

### Provider

Sflix 

### Reproduction steps

![Screenshot_20240908-181708](https://github.com/user-attachments/assets/27e2b2fa-43dc-4677-8354-e9b1c5380e64)
![Screenshot_20240908-181705](https://github.com/user-attachments/assets/f571877b-c6bb-4497-a4f4-6f44ff53c88b)

### Operating system

Google TV

### Please confirm the following

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] If related to a provider, I have checked the site and it works, but not the app.

**Comment by Vickyhawk** [comment]
Same issue. http error 404 for sflix. What is the wayout guys?

**Comment by ANastronaut01** [comment]
same here.
http 404 both at Vidcloud and Upcloud

**Comment by Nobry-Lab** [comment]
I have had this same issue for almost a week now. 
![Screenshot_2024-09-14-12-13-22-798_com tanasi streamflix](https://github.com/user-attachments/assets/a7d1a58f-6c01-4c1c-829c-d16c7d76e90c)
![Screenshot_2024-09-14-12-13-19-043_com tanasi streamflix](https://github.com/user-attachments/assets/0ed2cdf6-1cdd-4643-b45f-64f361c455e6)

**Comment by stantanasi** [comment]
For now, try to use TMDb provider

**Comment by stantanasi** [comment]
**Fixed on Release 1.6.12**

**Comment by Nobry-Lab** [comment]
Same Problem reoccured as per today Sunday 22nd!
