### ISSUE TITLE
Opensubstitle works fine but originally embedded subtitles list is missed.

### ISSUE THREAD

**Issue by Benlee1129** [stantanasi/streamflix#166]
### Description

As title is said, please check the bugs.
By the way, vidsrc.xyz seems a better server than vidsrc.net.

### Provider

TMDB

### Reproduction steps

Captions 

### Operating system

Android 

### Please confirm the following

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] If related to a provider, I have checked the site and it works, but not the app.

**Comment by stantanasi** [comment]
It's normal that you don't have any embedded subtitle using Vidsrc.net server, because Vidsrc.net doesn't have them. On web, it uses OpenSubtitles to retrieve subtitles, so I do the same.

> By the way, vidsrc.xyz seems a better server than vidsrc.net.

Will look into it, thanks
