### ISSUE TITLE
Put "specials" to the end of the seasons list

### ISSUE THREAD

**Issue by oathzed** [stantanasi/streamflix#168]
### Summary

Small change, but I'd suggest putting "specials" to the end of the seasons list, they're usually something that is watched when there are no seasons left to watch, if at all. The first thing the person should see in the list is the first season to watch because that's the most important thing. Apps like stremio sort it at the end also.

Thanks 🙏!

### Please confirm the following

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.

**Comment by stantanasi** [comment]
**Available on Release 1.6.12**
