### ISSUE TITLE
Continue watching section refinement

### ISSUE THREAD

**Issue by oathzed** [stantanasi/streamflix#169]
### Summary

The continue watching section works great, the only thing I'd suggest changing is how it should populate next episodes.

**How it should work:**

For example: if I finishing watching S1E1 of breaking bad, then press back to home, it should put S1E2 of breaking bad in my continue watching section. This way we can easily pick up with where we left of from a show, instead of having to go search for the show again or instead of having to find it in our favourites. If you've now watched all the episodes of a show, obviously nothing for that show will now be in your continue watching section. 

The only thing that will remove a show from your continue watching is if you long press it "remove from continue watching". However, if I decide I'd like to pick up again with that show it will start getting added back to my continue watching section.

 If you long press and item in your continue watching and sary "mark as watched S1E2" it will refresh the page and have s1e3 of that title now in the continue watching section.

**How the app currently functions:**

If I watch S1E1 of "breaking bad"to the end, and press back to the home screen, no S1E2 will be in the continue watching section.

### Please confirm the following

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.

**Comment by stantanasi** [comment]
Should be available on next release!

<br/>

> The only thing that will remove a show from your continue watching is if you long press it "remove from continue watching".

This one, I did not implement it because it will changes a lot of my codes, and will take some time. But I will try to implement it soon.

**Comment by oathzed** [comment]
> Should be available on next release!
> 
> 
> > The only thing that will remove a show from your continue watching is if you long press it "remove from continue watching".
> 
> This one, I did not implement it because it will changes a lot of my codes, and will take some time. But I will try to implement it soon.

Awesome, that sounds good man. Look forward to trying the new release out

**Comment by stantanasi** [comment]
**Available on Release 1.7.1**

**Comment by stantanasi** [comment]
> The only thing that will remove a show from your continue watching is if you long press it "remove from continue watching".

**Available on Release 1.7.2**
