### ISSUE TITLE
When on the side menu, featured images don't change

### ISSUE THREAD

**Issue by oathzed** [stantanasi/streamflix#171]
### Description

When you're in the homepage but you go to the side menu, only the text changes, the images don't change, until you go back out of the side menu 

### Provider

Tmdb

### Reproduction steps

1. Go to the home screen
2. Now open the side menu
3. And just look at the home menu featured items, the image will not update
See video: https://imgur.com/a/YovBtzc

### Operating system

Shield android tv

### Please confirm the following

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] If related to a provider, I have checked the site and it works, but not the app.

**Comment by stantanasi** [comment]
@oathzed I just saw why there is this problem and why I coded this way, I'll try to find a solution

**Comment by oathzed** [comment]
> @oathzed I just saw why there is this problem and why I coded this way, I'll try to find a solution

Thanks 🙏

**Comment by stantanasi** [comment]
**Fixed on Release 1.6.12**
