### ISSUE TITLE
"Casts" > should be singular: Cast

### ISSUE THREAD

**Issue by oathzed** [stantanasi/streamflix#172]
### Description

This is a small fix lol, but just want to help make your app perfect ❤️.On the show or movie page, it currently says "Casts" this should be "Cast"

Like this:
![PXL_20240913_155309421 MP~2](https://github.com/user-attachments/assets/50040721-5103-4a3f-85db-6a0899ccdd73)

### Provider

Tmdb

### Reproduction steps

1. Go to a tv show or movie
2. See Casts, that should be Cast :P

### Operating system

Shield tv

### Please confirm the following

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] If related to a provider, I have checked the site and it works, but not the app.

**Comment by stantanasi** [comment]
Thanks
