### ISSUE TITLE
Rabbitstream API site url error

### ISSUE THREAD

**Issue by depezo** [stantanasi/streamflix#173]
### Description

I think the problem with the Sflix provider is the API link for rabbitstream, the API does not respond, the netlify site url where the API is hosted is inaccessible.

<img width="593" alt="rabbitstream" src="https://github.com/user-attachments/assets/aff3d8e9-d57d-4ec1-8054-4f69459c5323">

### Provider

Sflix

### Reproduction steps

Open App
Select Sflix provider
Choose a movie
Click "Watch now" Button

### Operating system

Android 14

### Please confirm the following

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] If related to a provider, I have checked the site and it works, but not the app.

**Comment by stantanasi** [comment]
Yes, I know, thanks
The developer who created this API said that it was removed because too many people were using it and that it was deployed with a free subscription, so it had a request limit.

When I will have news, I will try to update it

**Comment by depezo** [comment]
Thank you very much for reply, but if the API is Open Source, he can give us either the API link so we can do what is necessary to host it.

**Comment by stantanasi** [comment]
I don't know him, and I don't know if its OpenSource also. I saw this on Discord

**Comment by depezo** [comment]
Ok

**Comment by stantanasi** [comment]
**Fixed on Release 1.6.12**
