### ISSUE TITLE
Only embedded Chinese-traditional subtitle is unable to be gotten on Sflix provider.

### ISSUE THREAD

**Issue by Benlee1129** [stantanasi/streamflix#178]
### Description

When Chinese-traditional caption is selected, the Chinese-simplfied one is enforcedly gotten. That's weird to me. Other subtitles are all working great but merely Chinese-traditional is not picked up.
I test original resources on Sflix.to website and there is no such problem. Is there the retrived caption gone wrong local link?

### Provider

Sflix

### Reproduction steps

1. Go to sflix provider
2. Captions 
3. Chinese-traditional 

### Operating system

Android 14

### Please confirm the following

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] If related to a provider, I have checked the site and it works, but not the app.

**Comment by stantanasi** [comment]
Thanks I didn't see that, my bad

**Comment by stantanasi** [comment]
**Fixed on Release 1.6.13**
