### ISSUE TITLE
Display place of birth and age under actors name on their detail page

### ISSUE THREAD

**Issue by oathzed** [stantanasi/streamflix#180]
### Summary

Would be awesome to get some more info on the actors, whenever I'm watching movies with people were usually like how old is that guy or where is he from.

Being able to pull that info from TMDb would be great, personally I'd display it in this order:

Colin Farrell
Place of birth: Castleknock, Dublin, Ireland
Born: May 31, 1976 (48 years old)

![PXL_20240920_233857020 MP~3](https://github.com/user-attachments/assets/0bae8619-7a27-4792-8805-0ac3069ba3e3)

Thanks! And let me know if I'm tiring you with these requests lol. I feel like the app is near perfect as far as features/UI, just thinking of a few things that would improve it.

### Please confirm the following

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.

**Comment by stantanasi** [comment]
Done, should be available in next release!

> And let me know if I'm tiring you with these requests lol

Not a all! Your requests are always welcome, and I’m happy to improve the app. Sometimes I just don't have time to answer, implement what you asking for, or I don't know how to do it, but it helps me to know all the things that can be improve.

And I look regularly your previous requests, but I still don't know how to fix or implement thoses 😅

**Comment by oathzed** [comment]
> Done, should be available in next release!
> 
> > And let me know if I'm tiring you with these requests lol
> 
> Not a all! Your requests are always welcome, and I’m happy to improve the app. Sometimes I just don't have time to answer, implement what you asking for, or I don't know how to do it, but it helps me to know all the things that can be improve.
> 
> And I look regularly your previous requests, but I still don't know how to fix or implement thoses 😅

Thanks man!

I appreciate that. You're honestly the most responsive dev ive ever seen and always great at adding/fixing stuff, so I really thank you for taking the time with all this.

Haha, maybe one day you'll figure it out, but all good if you don't ❤️

**Comment by stantanasi** [comment]
**Available on Release 1.7.1**
