### ISSUE TITLE
Footer

### ISSUE THREAD

**Issue by merdanch** [stantanasi/streamflix#182]
### Summary

Hello, Really appreciate for the great app and efforts.

On TV, I wanted to add same as like Header but on the bottom single [NavigationSlideView](navigation/src/main/java/com/tanasi/navigation/widget/NavigationSlideView.kt) item  can you help me to achieve this thanks 

### Please confirm the following

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.

**Comment by stantanasi** [comment]
I took so much time on doing the navigation slide view on the left, so if it's not already implemented by Android, you will have to do it yourself from scratch.
Not sure if I can help you
