### ISSUE TITLE
Encryption key problem

### ISSUE THREAD

**Issue by Tonikrs8** [stantanasi/streamflix#185]
### Description

Whenever tries to play on Hianime it says "Can't retrieve encryption key".
The website is working perfectly fine.

### Provider

HiAnime

### Reproduction steps

1. Go to HiAnime
2. Try to stream any content
3. It shows error

### Operating system

Android TV

### Please confirm the following

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] If related to a provider, I have checked the site and it works, but not the app.

**Comment by stantanasi** [comment]
I had something like this too, normally it sould be 100% fixed on Release 1.7.0
