### ISSUE TITLE
Add 10 seconds skip with D-Pad

### ISSUE THREAD

**Issue by KingNothing81** [stantanasi/streamflix#189]
### Summary

Hi ...

I think it would be nice if it was possible to skip back/forward 10 seconds by pressing left/right on the D-Pad during video playback. 

I'm used to doing this from many other streaming apps, so it would be great if it would also work in StreamFlix.

Thanks.

### Please confirm the following

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.

**Comment by oathzed** [comment]
That has already been suggested here: https://github.com/stantanasi/streamflix/issues/33

**Comment by KingNothing81** [comment]
Ah ... ok. Sorry I missed it.

And can I change your mind about this? ;)

Because pressing left/right to skip forward/back works in many famous streaming apps. For example Netflix, Prime Video, Disney+ and even in Kodi with the default configuration. So I think it's more confusing for users if this doesn't work than the opposite.

But you are the boss of course. =)

**Comment by stantanasi** [comment]
Well currently, you can skip back/forward by going to the video player seek bar, then pressing left/right.

But if you still want to skip back/forward directly from the play/pause button, I will do that. For me, it's not a good idea, but as you want lol

**Comment by oathzed** [comment]
> Well currently, you can skip back/forward by going to the video player seek bar, then pressing left/right.
> 
> But if you still want to skip back/forward directly from the play/pause button, I will do that. For me, it's not a good idea, but as you want lol

I think it's more intuitive cause that's how Netflix does it, so I guess more people are used to it xD

**Comment by KingNothing81** [comment]
> Well currently, you can skip back/forward by going to the video player seek bar, then pressing left/right.
> 
> But if you still want to skip back/forward directly from the play/pause button, I will do that. For me, it's not a good idea, but as you want lol

One of the reasons I would like to do it is that I can skip without having to bring up the video player each time. So if you really implement the feature, I would prefer if skipping directly works without the video player UI showing up.

Or what's @oathzed opinion about this?

**Comment by oathzed** [comment]
> > Well currently, you can skip back/forward by going to the video player seek bar, then pressing left/right.
> > But if you still want to skip back/forward directly from the play/pause button, I will do that. For me, it's not a good idea, but as you want lol
> 
> One of the reasons I would like to do it is that I can skip without having to bring up the video player each time. So if you really implement the feature, I would prefer if skipping directly works without the video player UI showing up, but to keep it hidden.
> 
> Or what's @oathzed opinion about this?

I would agree with you for the most part, one small thing I would want is have the seek bar peek through at the very bottom of the screen just enough so you can see how far you're seeking. Not the full UI screen, just a very small thing so it doesn't cover anything important

**Comment by KingNothing81** [comment]
I skip a lot, because I have sometimes have some problems understanding dialog. And personally I don't like if the player UI pops up everytime I do. 

So for me the perfect solution would be to keep the video player hidden if you only do the 10 sec skips. But to show it (or only the progress bar) when you hold left/right to start fast forwarding / rewinding through the video.

But I'll take whatever is acceptable for @stantanasi. ;)

**Comment by stantanasi** [comment]
Okay I'll see what I can do

**Comment by KingNothing81** [comment]
@stantanasi Thanks for your effort. I really like to be able to do the skips directly now. And in my opinion this makes the app more comfortable to use on TV. 

Maybe for a future version I think it would be nice to show a little icon on screen that indicates that you are doing a 10 sec skip. Something like [this](https://www.google.com/search?client=safari&sca_esv=251e5a0e8da88d6a&hl=de-de&q=icon+skip+10+seconds&udm=2&fbs=AEQNm0A6bwEop21ehxKWq5cj-cHa02QUie7apaStVTrDAEoT1FdmHTSMJP_rxgj2yFrTtBlkQVsLjwuKFMBZ-y4XWi8DMNtmh3kUksrc4v5-Zp-AjgmpNJKZVYwF7Zc5b1IGJi-WScCfKx-jrePn4IgQ6oRn7YjL3-j3BO-6QnkgknSB7JfkLgOoA3UIaKkDEcQ5wtvVfojf9lVPFkgLbj_R3Xy3-qgVmQ&sa=X&ved=2ahUKEwjKi76Jzc2JAxVJ2wIHHRfWJ1AQtKgLegQIFBAB&biw=768&bih=921&dpr=2).

By the way: Have you thought about adding  automatic frame rate matching to the TV app? That would really rock. =)

**Comment by stantanasi** [comment]
> Maybe for a future version I think it would be nice to show a little icon on screen that indicates that you are doing a 10 sec skip. Something like this

Good idea, I didn't think about that. I will try to add it next time.

> By the way: Have you thought about adding automatic frame rate matching to the TV app? That would really rock. =)

I don't understand what you mean by "automatic frame rate matching to the TV app", can you explain it please

**Comment by KingNothing81** [comment]
> I don't understand what you mean by "automatic frame rate matching to the TV app", can you explain it please

Some apps (like “Kodi” or YT client “SmartTube”) support this. They can automatically adjust the display mode, so the refresh rate of the display matches the frame rate of the video. This helps to get smooth video playback without micro stuttering, especially on TVs.

Here is a developer article about this, if you want to know more:

https://developer.android.com/media/optimize/performance/frame-rate

**Comment by stantanasi** [comment]
Okay I see, I'm not sure if I can do this but I will look into it

**Comment by KingNothing81** [comment]
> Okay I see, I'm not sure if I can do this but I will look into it

No problem. But if you will, I think using the described “preferredDisplayModeId” method would be the best choice, as it will also work on older devices (< Android 11). 

Thanks.
