### ISSUE TITLE
Pouvez-vous mettre à jour le lien français 1jour1film il ne fonctione pas ? .

### ISSUE THREAD

**Issue by Logami61** [stantanasi/streamflix#193]
### Description

https://1jour1film.pics est devenu https://1jour1film.skin  merci 

### Provider

1jour1film

### Reproduction steps

1jour1film a changé de nom est devenu https://1jour1film.skin  j'ai fait une deuxième version en attendant la mise à jour code pour downloader 900262  OU https://www.mediafire.com/file/2a6sqjru9ks36by/STREAM_V2.apk/file

### Please confirm the following

- [x] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] If related to a provider, I have checked the site and it works, but not the app.

**Comment by stantanasi** [comment]
**Changé sur la version 1.7.2**
