### ISSUE TITLE
bug 

### ISSUE THREAD

**Issue by boris50460** [stantanasi/streamflix#197]
### Description

Multi hd 1080p: error:1e000065:cipher function....

### Provider

francais

### Reproduction steps

Multi hd 1080p: error:1e000065:cipher function....

### Logs

```bash
Multi hd 1080p: error:1e000065:cipher function....
```

### Please confirm the following

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] If related to a provider, I have checked the site and it works, but not the app.

**Comment by stantanasi** [comment]
Je viens de tester, ça m'a l'air de fonctionner.
Peut-tu être plus spécifique sur où survient le bug en question : quelles providers (1JOUR1FILM ?) ? quelle film ou série ? quelle épisode si c'est une série ?....
