### ISSUE TITLE
Pouvez-vous incorporer un site d'anime français ?

### ISSUE THREAD

**Issue by Xx-nanico-xX** [stantanasi/streamflix#200]
### Summary

bonjour je trouve votre projet incroyable , et je me demandais si c'était possible d'y ajouter un site d'anime français comme https://french-anime.com/ ou  https://anime-sama.fr/ 
je vous remercie encore pour ce projet .

### Please confirm the following

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.

**Comment by stantanasi** [comment]
**J'ai ajouté Otakufr sur la nouvelle version 1.7.8**
Je verrais si j'ajoute d'autres
