### ISSUE TITLE
problème résolu merci

### ISSUE THREAD

**Issue by Xx-nanico-xX** [stantanasi/streamflix#210]

**Comment by Linkinep61** [comment]
il y a eu une maintenance sur leur site  et ils ont fait un site miroir de https://1jour1film.skin/ a https://videofutur.skin/ cela peut vous faire un deuxième provider français sans rien faire  a +

**Comment by electrosat25** [comment]
comment résoudre le problème de l'application qui se ferme à l'ouverture
merci de votre réponse
