### ISSUE TITLE
Apk ne s'ouvre plus

### ISSUE THREAD

**Issue by Jeje2308** [stantanasi/streamflix#211]
### Description

Quand j'ouvre l'application, elle se referme automatiquement streamflix

### Provider

Streamflix 

### Reproduction steps

Quand j'ouvre apk elle se referme automatiquement

### Operating system

Android 12

### Please confirm the following

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] If related to a provider, I have checked the site and it works, but not the app.

**Comment by Lionel62880** [comment]
Bonjour, j'ai le même souci

**Comment by Jeje2308** [comment]
Bonjour sa viens de la application merci

**Comment by stantanasi** [comment]
**Résolu sur la [Release 1.7.4](https://github.com/stantanasi/streamflix/releases/latest)**, du coup il faudra retélécharger l'APK vu que l'app ne se lance pas

**Comment by Jeje2308** [comment]
Merci

Le dim. 3 nov. 2024, 22:08, Lory-Stan TANASI ***@***.***> a
écrit :

**Comment by stantanasi** [comment]
> Sur iPhone ça ne fonctionne pas ?

Non

**Comment by Jeje2308** [comment]
Ok merci

Le lun. 4 nov. 2024, 13:24, Lory-Stan TANASI ***@***.***> a
écrit :

**Comment by Jeje2308** [comment]
Depuis mise à jour plus en français 😡

**Comment by stantanasi** [comment]
> Depuis mise à jour plus en français 😡 Le lun. 4 nov. 2024, 13:30, Jerome Jerome ***@***.***> a écrit :

Les administrateurs du site français m'ont demandé de supprimer leurs sites
