### ISSUE TITLE
APP CRASH ON LAUNCH

### ISSUE THREAD

**Issue by github-jl14** [stantanasi/streamflix#212]
### Description

i installed the newest and it's always exiting after the splash screen. (i tried the mobile only and the base version)

### Provider

n/a (happend on app launch, not in any provider)

### Reproduction steps

1. Install app
2. open it
3. Crash

### Operating system

android 11

### Logs

```bash
idk where's the log?
```

### Please confirm the following

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] If related to a provider, I have checked the site and it works, but not the app.

**Comment by Linkinep61** [comment]
le provider de StreamingCommunityProvider  rendre l'application non fonctionnel  suffit de le supprimer et ça refonctionne et aussi aller dans provider et supprimer  StreamingCommunityProvider,

**Comment by winnibouba** [comment]
The same for me on Android TV (NVIDIA Shield Android 11) and on smartphone android 13

**Comment by winnibouba** [comment]
> le fournisseur de StreamingCommunityProvider rendre l'application non fonctionnelle suffit de le supprimer et ça refonctionne et aussi aller dans fournisseur et supprimer StreamingCommunityProvider,

With a Italian vpn, it's work
How te remove StreamingCommunityProvider ?

**Comment by Linkinep61** [comment]
avec Android studio tu peux faire la modif ou va sur YouTube ( La meilleur Application sur Android TV Fire TV et Google TV) il ya un cod dans les commentaires  ça pourra te dépanner

**Comment by winnibouba** [comment]
Thanks for your answer
it seems complicated to use android studio and I don't see what to do with the code either I will wait for an update of the application

**Comment by stantanasi** [comment]
> le provider de StreamingCommunityProvider rendre l'application non fonctionnel suffit de le supprimer et ça refonctionne et aussi aller dans provider et supprimer StreamingCommunityProvider,

Bien vu, j'ai réglé le soucis. Et désolé j'aurais dû mieux regarder lorsque le code a été ajouté.

**Comment by stantanasi** [comment]
**Résolu sur la [Release 1.7.4](https://github.com/stantanasi/streamflix/releases/latest)**, du coup il faudra retélécharger l'APK vu que l'app ne se lance pas
