### ISSUE TITLE
l'application se ferme à l'ouverture 

### ISSUE THREAD

**Issue by electrosat25** [stantanasi/streamflix#213]
### Description

L'application se ferme à l'ouverture, hier elle marche très bien, aujourd'hui impossible d'ouvrir l'application
Que faire svp, car cette application est merveilleuse 

### Provider

streamflix 

### Reproduction steps

Impossible d'ouvrir l'application elle se ferme à l'ouverture 

### Operating system

Android 12

### Please confirm the following

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] If related to a provider, I have checked the site and it works, but not the app.

**Comment by Linkinep61** [comment]
yo va sur YouTube (La meilleur Application sur Android TV Fire TV et Google TV)  et regarde les commentaires

**Comment by stantanasi** [comment]
Duplicate of #211

**Comment by stantanasi** [comment]
**Résolu sur la [Release 1.7.4](https://github.com/stantanasi/streamflix/releases/latest)**, du coup il faudra retélécharger l'APK vu que l'app ne se lance pas

**Comment by stantanasi** [comment]
La version 1.7.4 ? Celle qui est sortie hier soir ?

**Comment by electrosat25** [comment]
Elle marche très bien la version 1.74
merci aux développeurs
