### ISSUE TITLE
Captions are not working with MULTI source

### ISSUE THREAD

**Issue by Mfgaz** [stantanasi/streamflix#214]
### Description

Hello,
Great app thx. However, subtitles (in any language) are not displayed with a MULTI source. I've tried “French” or “English” subtitles with “English” audio for the LEE MILLER movie with the “1jour1film” provider and it doesn't work. 
The subtitles are working via the provider website but not via Streamflix.

### Provider

1 Jour 1 Film

### Reproduction steps

![no_subtitles](https://github.com/user-attachments/assets/b0f1aee9-e654-4055-8319-e67684bef605)

### Operating system

Android 14.11 (S24+ One UI 6.1)

### Please confirm the following

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] If related to a provider, I have checked the site and it works, but not the app.

**Comment by stantanasi** [comment]
Thanks I understand the problem.
Before fixing it, can I be sure that it happens on all servers (from 1Jour1Film), or only on some servers (only MULTI as you said) ? Did you manage to have subtitle on some movie or not ?

**Comment by fminssieux** [comment]
Same problem here, the only way I can get subtitles to work is by loading an external file.

**Comment by Mfgaz** [comment]
Thx a lot for your answer! I have the problem with all multi sources. I have to select a MULTI source if I want the original audio with french subtiles. I've tried several movies and all available french subtitles (french1, french2, etc) and get no subtitle at all. Regards, MG

**Comment by stantanasi** [comment]
Thanks

**Comment by stantanasi** [comment]
**Fixed on Release 1.7.5**

**Comment by Mfgaz** [comment]
Perfect!! It works fine with your new release! Good job!!
