### ISSUE TITLE
Streamflix 

### ISSUE THREAD

**Issue by electrosat25** [stantanasi/streamflix#216]
### Description

Avec la version 1.74 installée hier tout est parfait, aujourd'hui aucun film ou séries ne marche toujours erreur http 400

### Provider

streamflix 

### Reproduction steps

Avec la version 1.74 installée hier tout est parfait, aujourd'hui aucun film ou séries ne marche toujours erreur http 400

### Operating system

Android Google tv 

### Please confirm the following

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] If related to a provider, I have checked the site and it works, but not the app.

**Comment by stantanasi** [comment]
Duplicate of #217
