### ISSUE TITLE
[1JOUR1FILM] Error HTTP 400 

### ISSUE THREAD

**Issue by electrosat25** [stantanasi/streamflix#217]
### Description

Avec la version 1.74 installée hier tout est parfait, aujourd'hui aucun film ou séries ne marche toujours erreur http 400

### Provider

1JOUR1FILM 

### Reproduction steps

- Regarder 1 film ou un épisode d'une série
- Message d'erreur HTTP 400 s'affiche

### Operating system

Android Google tv 

### Please confirm the following

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] If related to a provider, I have checked the site and it works, but not the app.

**Comment by stantanasi** [comment]
Dis moi ça sert à quoi d'envoyer 1 message, créer 2 issue pour exactement la même chose (alors qu'en plus c'est possible de les modifier au lieu d'en créer un nouveau).
Bref, après avoir testé tous les providers (parce qu'en plus tu dis même pas dans lequel se trouve le problème), je vois où ça se trouve et je vais regarder.

**Comment by electrosat25** [comment]
désolé d'avoir envoyé deux messages pour un seul problème. je ne sais pas
encore utiliser le site
le problème
c'est un jour un film
merci beaucoup vous faites un travail formidable

Le ven. 8 nov. 2024, 15:14, Lory-Stan TANASI ***@***.***> a
écrit :

**Comment by stantanasi** [comment]
**Résolu sur la version 1.7.6**

**Comment by electrosat25** [comment]
Merci
