### ISSUE TITLE
Francais à venir

### ISSUE THREAD

**Issue by kris06000** [stantanasi/streamflix#224]
### Summary

Avez vous prevu un serveur de remplacement pour la langue francaise ?
C'est  très regretable que vous avez été contraint de retirer le precedent...

### Please confirm the following

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.

**Comment by Aqwaqw12** [comment]
S il te plait on a besoin des films en français et merci
