### ISSUE TITLE
it dosen't work

### ISSUE THREAD

**Issue by haydourriahi** [stantanasi/streamflix#226]
![ec3dcbbf-023f-4489-8ee4-9a9f9a690d56](https://github.com/user-attachments/assets/9ad62359-27c9-46e7-878c-d9d0973d666e)
### Description

whenever i try to open a show or a movie it says no extractore found an it just stay black

### Provider

All

### Reproduction steps

i open app
i choose an provider
i open a show 
it says no extractor found

### Operating system

All

### Please confirm the following

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] If related to a provider, I have checked the site and it works, but not the app.

**Comment by dom1201** [comment]
Same issue Here on Android TV
