### ISSUE TITLE
When you press search icon on the side, have the selector jump to the search bar

### ISSUE THREAD

**Issue by oathzed** [stantanasi/streamflix#25]
### Summary

when you press the search button on the side panel, have the selector jump to the search bar so all you have to do is press select and then start typing stuff.

Currently, you have to press right once, then up, then select it.

### Please confirm the following

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.

**Comment by stantanasi** [comment]
**Available on [Release 1.3.5](https://github.com/stantanasi/streamflix/releases/latest)**
