### ISSUE TITLE
Infinite scroll on lists/grids

### ISSUE THREAD

**Issue by oathzed** [stantanasi/streamflix#26]
### Summary

Would be great to be able to scroll through lists with it re-populating when you get to the end. Currently you can only view like 30 items.

### Please confirm the following

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.

**Comment by oathzed** [comment]
Ok awesome :D, thanks!

**Comment by DarkCrypt** [comment]
This would be a great improvement!

**Comment by stantanasi** [comment]
**Available on [Release 1.4.0](https://github.com/stantanasi/streamflix/releases/latest)**

**Comment by oathzed** [comment]
Hey man, everything else seems to be working great, but infinite scroll doesn't work on the home screen :o. is that possible?

**Comment by stantanasi** [comment]
> Hey man, everything else seems to be working great, but infinite scroll doesn't work on the home screen :o. is that possible?

No, that's not possible.
If you look for example at the [home page of the SFlix website](https://sflix.to/home), you will see that it is not possible to load more pages from the home page, same for other providers. So it is impossible for me to implement this.

**Comment by oathzed** [comment]
> > Hey man, everything else seems to be working great, but infinite scroll doesn't work on the home screen :o. is that possible?
> 
> No, that's not possible. If you look for example at the [home page of the SFlix website](https://sflix.to/home), you will see that it is not possible to load more pages from the home page, same for other providers. So it is impossible for me to implement this.

Ok thank you for explaining that, makes sense ☺️

**Comment by DarkCrypt** [comment]
This feature is bomb! 👍
