### ISSUE TITLE
Random crash

### ISSUE THREAD

**Issue by oathzed** [stantanasi/streamflix#27]
### Description

I was just playing a show "Blacklist" s10-e03, and then pressed back and back to homepage, and left the tv for a min, and it randomly closed the app, I wasn't even touching the remote.

Not sure how to get a log for you, maybe a debug version can be made?

### Reproduction steps

1. play Blacklist s10e03 from latest tv shows on homepage
2. press back to homepage
3. wait for crash? not sure if this had anything to do with it

### App version

v1.3.1 (Latest)

### Operating system

shield android tv

### Please confirm the following

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] If related to a provider, I have checked the site and it works, but not the app.

**Comment by stantanasi** [comment]
Okay thank you for all those informations, I'll look into it.

**Comment by oathzed** [comment]
I'm gonna close this issue, I haven't noticed any crashing with the new update and i've been testing it a lot
