### ISSUE TITLE
Have it remember your provider on exit

### ISSUE THREAD

**Issue by oathzed** [stantanasi/streamflix#28]
### Summary

Instead of choosing your provider when you open the app, have it just remember your last used provider, most of the time people aren't going to want to switch providers, and if they its at the top left corner already.

thanks!

### Please confirm the following

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.

**Comment by stantanasi** [comment]
I hesitated to implement this feature, but if users want it then it will be done!

**Comment by oathzed** [comment]
Awesome thanks! Yeh just makes it more seem less :)

**Comment by DarkCrypt** [comment]
I agree, this would be nice.

**Comment by DarkCrypt** [comment]
@optzeci 
The option to select Auto quality is available in player settings. Maybe this doesn't work the same as your request?

**Comment by stantanasi** [comment]
Sorry for taking so much time for answering this, I was taking some time for myself!

> It would also be great if the app would remember the language of the subtitle you previously chose, so that you won't have to manually select the subtitle for each movie. Or at least to have a setting somewhere in the app to select the subtitle language for all the movies that you will watch.

It could be hard to implement something like this, because the subtitle label is sometime differents between movies ("English" different from "English - English" or "English - SDH"), but I could try...

> It could be the same for the quality. To be able to select for example Auto and depending on the availability on Sflix, the app to first select 1080p and only when 1080p is not available, to get to 720p.

Okay I will look into it!

**Comment by optzeci** [comment]
> @optzeci 
> 
> Sorry for taking so much time for answering this, I was taking some time for myself!
> 
> > It would also be great if the app would remember the language of the subtitle you previously chose, so that you won't have to manually select the subtitle for each movie. Or at least to have a setting somewhere in the app to select the subtitle language for all the movies that you will watch.
> 
> It could be hard to implement something like this, because the subtitle label is sometime differents between movies ("English" different from "English - English" or "English - SDH"), but I could try...
> 
> > It could be the same for the quality. To be able to select for example Auto and depending on the availability on Sflix, the app to first select 1080p and only when 1080p is not available, to get to 720p.
> 
> Okay I will look into it!
> 



No worries mate. Take your time. You and your family are more important than an app 😁

Thanks anyway for answering and looking forward to the next release, whenever it will be possible.

Take care and thanks for this nice app!

**Comment by oathzed** [comment]
@stantanasi you are crushing these big reports/feature requests. Nice work man

**Comment by stantanasi** [comment]
Thanks, I took a 2 month break so I have to be productive when I get back haha 🤣

**Comment by stantanasi** [comment]
**Available on [Release 1.3.3](https://github.com/stantanasi/streamflix/releases/latest)**

**Comment by DarkCrypt** [comment]
App remembers provider on exit v1.3.3. Very nice!
