### ISSUE TITLE
When you select a side button have it minimize and open go to the first item

### ISSUE THREAD

**Issue by oathzed** [stantanasi/streamflix#30]
### Summary

Basically, when you select "home" on the side, have the side panel minimize automatically like it does when you press right to go to the first item. cuts down on an extra click, better UX

Currently you select "home" it will stay on the side menu and you have to press right to get to the first item.

### Please confirm the following

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.

**Comment by stantanasi** [comment]
**Available on [Release 1.3.5](https://github.com/stantanasi/streamflix/releases/latest)**
