### ISSUE TITLE
When you first open the app, the backdrop doesnt load on Home

### ISSUE THREAD

**Issue by oathzed** [stantanasi/streamflix#32]
### Description

When you first open the app, inside home backdrop for that title won't show until you enter home

### Reproduction steps

1. Start the app fresh
2. Go to sflix
3. See no backdrop on home
4. To see it, enter home

Video below:

https://imgur.com/a/swIsNlE

### App version

v1.3.1 (Latest)

### Operating system

Shield android tb

### Please confirm the following

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] If related to a provider, I have checked the site and it works, but not the app.

**Comment by DarkCrypt** [comment]
I thought this was strange too.

**Comment by stantanasi** [comment]
**Fixed on [Release 1.3.5](https://github.com/stantanasi/streamflix/releases/latest)**
