### ISSUE TITLE
Move the play/pause button here, and have left and right fast forward right away

### ISSUE THREAD

**Issue by oathzed** [stantanasi/streamflix#33]
### Summary

To save a couple clicks and create better UX, move the play pause button beside the seeker.

So if you pres left or right it will fast forward or rewind right away. Currently you have to press select then press down then you can fast forward/rewind.

I know there are fast forward/rewind buttons on some remotes, but some remotes don't have though, and this is just easier to use UX with the left and right nav. This will save 2 clicks.

Picture for look:

https://imgur.com/a/99LsRWS

### Please confirm the following

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.

**Comment by stantanasi** [comment]
I think putting play/pause button beside the seekbar might be confusing for the users to understand how to navigate through the player.

I prefer to leave the play/pause button in the center of the player for now, but I could implement to forward/rewind directly from the play/pause button.
To clarify, I could:
- Press select (focus on play/pause), then right/left to forward/rewind
- As before, press select, then down, then forward/rewind

**Comment by oathzed** [comment]
Ok, yeh this sounds like a great option:

"Press select (focus on play/pause), then right/left to forward/rewind"

**Comment by oathzed** [comment]
Can you make it, so you don't have to press play/pause to start rewinding/ fast forwarding?

that way you can just hold left or right without having to first open the player UI. when you start fast forwarding/rewinding a seek bar can pup up at the bottom to show how far back or forward you're going.

**Comment by stantanasi** [comment]
> Can you make it, so you don't have to press play/pause to start rewinding/ fast forwarding?
> 
> that way you can just hold left or right without having to first open the player UI. when you start fast forwarding/rewinding a seek bar can pup up at the bottom to show how far back or forward you're going.

First, I'll see if it's possible. Then maybe I'll implement it, I don't want the user to wrongly click the arrow buttons on their remote...

**Comment by oathzed** [comment]
Sounds good man thank you
