### ISSUE TITLE
When opening the app sometimes, instant crash/close

### ISSUE THREAD

**Issue by oathzed** [stantanasi/streamflix#34]
### Description

Sometimes if I have the app minimized for a while and I go to open it, it will crash right away and I have to press to open it again.

Seems like it may be going out of memory? Maybe there could be a better way to handle that? Instead of closing, refresh and start the app. 

### Reproduction steps

1. Open the app
2. Minimize the app
3. Leave it for a half a day maybe
4. Open it
5. Crash/closes and goes back to your Android tv home screen

### App version

v1.3.1 (Latest)

### Operating system

Shield android tv

### Please confirm the following

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] If related to a provider, I have checked the site and it works, but not the app.

**Comment by stantanasi** [comment]
I've never had a crash like this on my Chromecast Google TV, I'll try to recreate it and then fix it if I find the error.

**Comment by oathzed** [comment]
Hmm weird. Thanks for looking into it

**Comment by oathzed** [comment]
Gonna close this issue as well, I don't get this anymore with the latest update
