### ISSUE TITLE
Clear Button (X) In Search Bar

### ISSUE THREAD

**Issue by DarkCrypt** [stantanasi/streamflix#35]
### Summary

Users have to click the search bar and navigate to the delete button in the on-screen keyboard to delete text. There's no clear button or (X) in the search bar to quickly delete all text input on the search page. This would be very handy while using the remote and save users from doing this manually all the time.

Also, the only way to see the categories right now(after using the search bar) is to delete all text from the search bar and then hit search(blank search). Users may not understand how to get back to the categories and close/reopen the app in order to do so. It would be much more user friendly if the categories would appear after deleting the text from the search bar either manually or with quick clear.

### Please confirm the following

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.

**Comment by oathzed** [comment]
Do you think that launching proper voice search would be a better idea? whenever you search something it would auto clear and ask you to search for something else via voice. I guess this wouldn't help for the bottom categories though

**Comment by DarkCrypt** [comment]
@oathzed
You've mentioned many good recommendations on here recently and I agree with all of them. Bravo to you friend!

Proper voice search? Based on your explanation I don't think I've experienced this before, only the voice search built into the on-screen keyboard. Sounds interesting though. Using that method would you still be able to see the categories as long as the search bar was clear anyway or no? Otherwise, the only thing I can think of at the moment with that method would be to put a clickable button under the search bar to show categories but I was trying to avoid suggesting such a feature.

@stantanasi
Below is a screen recording of a similar app for mobile(I'm running it on WSA) that resembles what I was talking about with deleting text from search bar and displaying categories. This app doesn't have a clear button either.

https://user-images.githubusercontent.com/121076677/230239881-a92c7518-840f-4a41-9d34-a62c7b47a9f6.mp4

___
Since we're talking about the search bar, should the app also provide search suggestions or save previous searches that users are able to clear search history? I don't think either one of these features are absolutely necessary but many apps have 1 or both features. What do you guys think?

**Comment by oathzed** [comment]
> @oathzed You've mentioned many good recommendations on here recently and I agree with all of them. Bravo to you friend!
> 
> Proper voice search? Based on your explanation I don't think I've experienced this before, only the voice search built into the on-screen keyboard. Sounds interesting though. Using that method would you still be able to see the categories as long as the search bar was clear anyway or no? Otherwise, the only thing I can think of at the moment with that method would be to put a clickable button under the search bar to show categories but I was trying to avoid suggesting such a feature.


Thanks brotha! Good UX is nice xD.

Well, there technically is a leanback version of search on Android tv and it hasn't been implemented in this app, but how it works is you press search and it automatically pops up with voice trigger so you start speaking, if you don't want to speak you would pres to the right to go to the search bar and the keyboard pops up. This doesn't really have anything to do with your issue you posted but could be a good implementation to have. Not sure how it would work with the categories though.

For your clear all button, it could simply be an x at the right of the search bar and you press to the right to get to it.

**Comment by DarkCrypt** [comment]
Is this proper voice search baked into Android TV(is it the Google search icon?) or is there an app I can try this out? I'm curious.

> For your clear all button, it could simply be an x at the right of the search bar and you press to the right to get to it.

That's exactly what I was thinking. A lot of search bars work like this and would be easy for users to get to with a remote. Wouldn't be hard for stantanasi to implement either.

**Comment by oathzed** [comment]
> Is this proper voice search baked into Android TV(is it the Google search icon?) or is there an app I can try this out? I'm curious.
> 

It would have to be coded into the app, try Smartubenext

**Comment by DarkCrypt** [comment]
> It would have to be coded into the app, try Smartubenext

I tried this on SmartTubeNext and it is a handy feature. I like that idea but I don't think it'll be able to show the list of categories. If users would rather have this feature we need to come up with a different way to show categories.

**Comment by stantanasi** [comment]
Only added a clear button in search bar for now.
I'll see if I change or improve later.

**Comment by DarkCrypt** [comment]
Awesome! Clear button was the initial suggested improvement, plenty of time for future changes if you decide to do so. As always thank you friend.

**Comment by DarkCrypt** [comment]
I tried out the clear button and I noticed a few issues.

The clear button doesn't clear text and has no function:

1. After typing an inquiry in the search bar and immediately selecting clear button without doing a search.
2. After completing a search and immediately navigating to a different page in the side menu and then navigating back to the search bar.

**Comment by stantanasi** [comment]
**Available on [Release 1.3.3](https://github.com/stantanasi/streamflix/releases/latest)**

**Comment by DarkCrypt** [comment]
Clear button on v1.3.3 works great!
