### ISSUE TITLE
More people and more places in the world.

### ISSUE THREAD

**Issue by DVergil** [stantanasi/streamflix#36]
### Summary

I think more languages ​​and voiceovers would be great to expand the use of the app in more countries around the world.
The addition of 1080P quality and also if possible choose the codec or format of the video 

### Please confirm the following

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.

**Comment by DarkCrypt** [comment]
The choice of quality in 1080p, 720p, 360p, or Auto was implemented in v1.3.0. At the time of this comment v1.3.1 is the latest version. See stantanasi's comment in issue [#18](https://github.com/stantanasi/sflix/issues/18#issuecomment-1438199071).

**Comment by DVergil** [comment]
Thanks
