### ISSUE TITLE
request anime provider

### ISSUE THREAD

**Issue by ajimal173** [stantanasi/streamflix#38]
### Summary

deat sir,

pls add anime provider like allanime.to like that or which u preferer but pls add if possible 

### Please confirm the following

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.

**Comment by stantanasi** [comment]
Add [Aniwatch](https://aniwatch.to) provider
**Available on [Release 1.3.5](https://github.com/stantanasi/streamflix/releases/latest)**

**Comment by ajimal173** [comment]
still i didn't check let me check n let u know thanks lot to add anime
provider as i requested....
