### ISSUE TITLE
Both providers down

### ISSUE THREAD

**Issue by mattstvmedia** [stantanasi/streamflix#39]
### Description

Sflix video doesn't launch 
All movies getting error is handshake failed

### Reproduction steps

Sflix video doesn't launch 
All movies getting error is handshake failed

### App version

v1.3.1 (Latest)

### Operating system

Fire tv 4k

### Please confirm the following

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] If related to a provider, I have checked the site and it works, but not the app.

**Comment by stantanasi** [comment]
Do you still have this error?

**Comment by kelvin2056** [comment]
I have error on loading movie today, similar issue to this.

**Comment by stantanasi** [comment]
**SFlix provider fixed**
