### ISSUE TITLE
can't access settings gear while watching on firetv

### ISSUE THREAD

**Issue by Akoi89** [stantanasi/streamflix#40]
### Description

I am unable to access the settings gear while watching movies on this app on my fire TV stick, works great on my nvidia shield tv box though. 

Any ideas or if anything could be implemented to make that possible to access? (Or I'm doing something completely wrong on my end?)

Thanks for the great app!

### Reproduction steps

Launch a movie or TV show and try to access the settings gear for subtitles/stream quality/etc with the remote. (Tried the remote and the remote app on my phone)

### App version

v1.3.1 (Latest)

### Operating system

fire TV stick latest os

### Please confirm the following

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] If related to a provider, I have checked the site and it works, but not the app.

**Comment by stantanasi** [comment]
Very weird I will try to look into it!

Is the movie running when trying to access settings? By that I mean I put a condition: until the movie is ready/loaded for the first time, the settings are not available.

**Comment by Akoi89** [comment]
> Very weird I will try to look into it!
> 
> Is the movie running when trying to access settings? By that I mean I put a condition: until the movie is ready/loaded for the first time, the settings are not available.

Yes, this is after the movie has started and everything. Appreciate it! Thank you!

**Comment by stantanasi** [comment]
And can you access the player's seek bar?
Or you can only play/pause the video without forward or backward

**Comment by KingLucius** [comment]
I am facing the same issue and yes i can forward/rewind without any issue

**Comment by stantanasi** [comment]
Probably tomorrow!
Just have to do some changes and check for bugs, then it will be available.

**Comment by Akoi89** [comment]
only other complaint I have with the firetv is when you fast forward through content it crashes the app if you go long distances.(happened a ton to me last night when I tried to rewind a show and it crashed and then I had to try getting back to my spot like 5+ times before it didnt crash it) I noticed it doesnt remember where you left off on a movie if you stop it either. I am using a Fire TV Stick 4K btw so it shouldnt be a limitation?

**Comment by stantanasi** [comment]
@Akoi89 Are you sure you use last version of the app, because it should remember where you left off (when you leave the movie between 3% ≈ 2min and 90%)?
If yes then I will have to check because on my Chromecast, there no problem!

**Comment by KingLucius** [comment]
I have tried, there is no any button in the remote control that open the settings. I can play/pause and forward/rewind without any issue

Also i have tried the crash bug when long forwarding and it's exist on my end.
FireTV stick 4k

**Comment by KingLucius** [comment]
I think this page can help you listen to "menu button" in firetv
https://developer.amazon.com/docs/fire-tv/remote-input.html

**Comment by stantanasi** [comment]
To access the settings button on my Chromecast, I use the directional pad on my remote (down + down + enter).
Does it work for you, if you use the D-pad?

**Comment by KingLucius** [comment]
1. There is no indicator for current focused UI item.
2. I have tried (down down enter ) and there is no effect. I think achieving the focus idicator will help me more.
3. I think using the "option/menu" buyton can make things easier

**Comment by stantanasi** [comment]
Okay, it does not work the same as on the Chromecast.
![image](https://github.com/stantanasi/streamflix/assets/46174829/74489cc3-f1f9-471a-bb11-934ca9f199c0)
![image](https://github.com/stantanasi/streamflix/assets/46174829/35eeac52-85a4-49a5-a5cc-9b2542812e00)

I'll have to do a lot more testing to see why it doesn't work.


> 3. I think using the "option/menu" button can make things easier 

Yeah, if users use the Fire TV Stick remote, I think too!

**Comment by KingLucius** [comment]
Ok take your time fizing it and if you need any debugging i can help you try anything on my end

**Comment by stantanasi** [comment]
If you have time, it would be my pleasure if you can test the **StreamFlix debug** app ([streamflix-debug.zip](https://github.com/stantanasi/streamflix/files/11637635/streamflix-debug.zip)).
And tell me if it is now possible to access the player's settings button using the directional arrows and/or the settings button on your remote control.

**Comment by Akoi89** [comment]
> @Akoi89 Are you sure you use last version of the app, because it should remember where you left off (when you leave the movie between 3% ≈ 2min and 90%)? If yes then I will have to check, because there no problem on my Chromecast!

I havent tried the new version you just posted yesterday yet but I will give it a try. but yeah the app crashed when I was fast forwarding and even after watching a movie for an hour it wouldnt let you resume after it crashed. On my shield TV I dont encounter any of these issues.

**Comment by KingLucius** [comment]
> If you have time, it would be my pleasure if you can test the **StreamFlix debug** app ([streamflix-debug.zip](https://github.com/stantanasi/streamflix/files/11637635/streamflix-debug.zip)).
> And tell me if it is now possible to access the player's settings button using the directional arrows and/or the settings button on your remote control.
> 
> PS: you will have two apps "StreamFlix" and "StreamFlix debug", when you finish testing, I recommend you to uninstall StreamFlix debug.

1. The current UI selected object indicator is appeared , i can now now which element i am over.
2. I can open the "gear" menu without an issue, but then i can't navigate in the opened menu.
3. The long seek bug is disappeared

**Comment by KingLucius** [comment]
Another addition:
The option button makes a sound without troggering anything

**Comment by Akoi89** [comment]
> > If you have time, it would be my pleasure if you can test the **StreamFlix debug** app ([streamflix-debug.zip](https://github.com/stantanasi/streamflix/files/11637635/streamflix-debug.zip)).
> > And tell me if it is now possible to access the player's settings button using the directional arrows and/or the settings button on your remote control.
> > PS: you will have two apps "StreamFlix" and "StreamFlix debug", when you finish testing, I recommend you to uninstall StreamFlix debug.
> 
>     1. The current UI selected object indicator is appeared , i can now know which element i am over.
> 
>     2. I can open the "gear" menu without an issue, only using pad directional keys, setting button is doing nothing but then i can't navigate in the opened menu.
> 
>     3. The long seek bug is disappeared

Yup, same thing here, with the debug release I can open the gear but can't navigate the options menu to change things (subtitles, quality, etc)

**Comment by stantanasi** [comment]
On the same principle, can you access the actors of a movie or TV show?

![image](https://github.com/stantanasi/streamflix/assets/46174829/060c0ed6-aeb3-4f0e-9f79-17c05ea4a55a)

**Comment by KingLucius** [comment]
No , i can't select

**Comment by stantanasi** [comment]
Okay, I figured out what the problem was. I'm fixing this right now.

**Comment by stantanasi** [comment]
**Available on [Release 1.3.3](https://github.com/stantanasi/streamflix/releases/latest)**
