### ISSUE TITLE
bad base-64

### ISSUE THREAD

**Issue by rhoncris** [stantanasi/streamflix#49]
### Description

error
![16902686650334626975819348974142](https://github.com/stantanasi/streamflix/assets/68005739/86b1354a-5301-4922-b3eb-633c745a706c)
.
waiting to fix this issue

### Reproduction steps

![1690268782520806422996804342990](https://github.com/stantanasi/streamflix/assets/68005739/a7cc13ec-25a0-4de7-9bfe-2eec8184be81)

### Logs

```bash
error
```

### Please confirm the following

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] If related to a provider, I have checked the site and it works, but not the app.

**Comment by stantanasi** [comment]
Already working on it ^^
Should be fixed today!

**Comment by stantanasi** [comment]
**Fixed on [Release 1.3.4](https://github.com/stantanasi/streamflix/releases/latest)**
