### ISSUE TITLE
No source is working anymore

### ISSUE THREAD

**Issue by optzeci** [stantanasi/streamflix#53]
### Description

I tried SFlix source and for all movies I get a HTTP 404 error when I try to play.

Changed to AnyMovie and I get a No extractors found error.

Also tested Anywatch and here again I get HTTP 404 error

I tested the website sflix.to and it works just fine. Anywatch.to also works just fine. Anymovies.xyz is working too. I don't know if these are the websites you are using to scrap from. 

Could you please check this issue and fix it in a future release?

Thanks in advance for your hard work 

### Reproduction steps

Try to play any movie using any of the 3 sources and you will get one of the above mentioned errors

### App version

1.3.5

### Operating system

Android TV 10.0 and Android TV 12.0

### Please confirm the following

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] If related to a provider, I have checked the site and it works, but not the app.

**Comment by stantanasi** [comment]
> I tried SFlix/Aniwatch source and for all movies I get a HTTP 404 error when I try to play.

I'm working on it. This should be fixed before Friday!

> Changed to AnyMovie and I get a No extractors found error.

I just saw that they changed their player, so I will need to implement a new extractor to fetch the video URL.
I will also try to fix it before Friday, but it might take longer.

**Comment by Jeanblake26** [comment]
we are willing to wait to fix this error thank you so much

**Comment by stantanasi** [comment]
**Fixed on [Release 1.3.6](https://github.com/stantanasi/streamflix/releases/latest)**

**Comment by optzeci** [comment]
Thanks! It's working good now. 🙏🏻
