### ISSUE TITLE
Add a star beside the rating

### ISSUE THREAD

**Issue by oathzed** [stantanasi/streamflix#54]
### Summary

just a small thing, but it will make it very obvious what that number means 
![Frame 36](https://github.com/stantanasi/streamflix/assets/52545913/d0aa47c1-51cb-41fe-ac1c-b7e9ee099453)

### Please confirm the following

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.

**Comment by oathzed** [comment]
> Okay no problem, I'm doing this right now!

thanks man!
I know you probably don't like giving out ETA's, but curious, are we far off from next release? xD

**Comment by stantanasi** [comment]
Probably in 2 hours max XD
Just time to do a few final tests to make sure everything works, and it will be out

**Comment by oathzed** [comment]
> Probably in 2 hours max XD Just time to do a few final tests to make sure everything works, and it will be out

Awesome! :D thanks man
