### ISSUE TITLE
No extractors found on AnyMovie provider

### ISSUE THREAD

**Issue by Mohd3rfan** [stantanasi/streamflix#55]
### Description

I cant play any movie.
1. Sflix provider says: 
![17026444949074548838668912975753](https://github.com/stantanasi/streamflix/assets/108115198/523ff68e-b727-4020-894f-f0d8edb0929e)

2. Anymovie provider says: 
![17026445390481087156295082946855](https://github.com/stantanasi/streamflix/assets/108115198/4de7bff5-c5b9-4597-bc3a-4bb54db25199)

### Reproduction steps

Click on whatever movie.

### App version

Latest

### Operating system

Haier android tv. Android 11

### Please confirm the following

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] If related to a provider, I have checked the site and it works, but not the app.

**Comment by stantanasi** [comment]
Looks like it's working now. Can you see if this is working on your end?

**Comment by Mohd3rfan** [comment]
> Looks like it's working now. Can you see if this is working on your end?

Sflix provider working now. TQ

But Anymovie still says 'no extractor founds', do i need to install extractor zip/rar or someting ? Just in case ?

**Comment by stantanasi** [comment]
> But Anymovie still says 'no extractor founds', do i need to install extractor zip/rar or someting ? Just in case ?

No, you don't have to do anything.  The problem with AnyMovie is that they changed their video player and I haven't implemented it yet.
It may take some time before it is fixed.
