### ISSUE TITLE
Add new options.

### ISSUE THREAD

**Issue by Zedmehi** [stantanasi/streamflix#56]
### Summary

Add next and previous option on tv-shows.

- Also add remove option for the watching section,please.

### Please confirm the following

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.

**Comment by stantanasi** [comment]
Completed in eafd9b1ce7dcbcb06268ca0ff10b478b17d87bce

**Comment by stantanasi** [comment]
**Available on [Release 1.5.0](https://github.com/stantanasi/streamflix/releases/latest)**
