### ISSUE TITLE
Subtitles improvement on the screen 

### ISSUE THREAD

**Issue by Moonir2** [stantanasi/streamflix#57]
### Summary

If possible, we want the on-screen subtitles format, such as stremio style.
Best Regards. 

### Please confirm the following

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.

**Comment by stantanasi** [comment]
Do you have an example screenshot?

**Comment by Chardyyy07** [comment]
Hello I Fix this through the settings of your Smart Tv by zooming out the screen resolution.
