### ISSUE TITLE
Add German provider

### ISSUE THREAD

**Issue by Jerico3241** [stantanasi/streamflix#58]
### Summary

s.to and aniworld.to both great websites

### Please confirm the following

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.

**Comment by Jerico3241** [comment]
OK nice Tahnk you very much 🤝

**Comment by stantanasi** [comment]
Wow man, thanks a lot!!!

**Comment by stantanasi** [comment]
**Available in [Release 1.5.2](https://github.com/stantanasi/streamflix/releases/latest)**

**Comment by stantanasi** [comment]
**Aniworld.to available in Release 1.7.2**
