### ISSUE TITLE
Some subtitle is not aligned 

### ISSUE THREAD

**Issue by Chardyyy07** [stantanasi/streamflix#59]
### Summary

Some subtitle is not aligned and my Android TV is Mi Stick plz fix thanks

### Please confirm the following

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.

**Comment by stantanasi** [comment]
Do you have a picture? 
And can you give me some movies or TV shows where you have this problem?

**Comment by Chardyyy07** [comment]
![IMG_20240102_210239.jpg](https://github.com/stantanasi/streamflix/assets/102837471/7c0c2c6b-b0bc-4366-9d6f-c5053ab1a2df)

![IMG_20240102_210034.jpg](https://github.com/stantanasi/streamflix/assets/102837471/f2379aee-34ab-40cf-9edc-0f951f839363)

![IMG_20240102_210052.jpg](https://github.com/stantanasi/streamflix/assets/102837471/4f0760e9-3d35-473c-abcf-5310661c74e7)

![IMG_20240102_210132.jpg](https://github.com/stantanasi/streamflix/assets/102837471/848ea98c-25a2-4e6e-8c82-1eca380185c5)

Please see this image for reference. 
The TV series image above are "Berlin" and "One Piece"

I usually encountered this when a New Series or movies came out. Also I think the app is not supported on my smart TV "Mi Tv Stick"cause its like a zoom a little bit. Thanks for the fast reply.

**Comment by Chardyyy07** [comment]
![IMG_20240102_210239.jpg](https://github.com/stantanasi/streamflix/assets/102837471/7c0c2c6b-b0bc-4366-9d6f-c5053ab1a2df)

![IMG_20240102_210034.jpg](https://github.com/stantanasi/streamflix/assets/102837471/f2379aee-34ab-40cf-9edc-0f951f839363)

![IMG_20240102_210052.jpg](https://github.com/stantanasi/streamflix/assets/102837471/4f0760e9-3d35-473c-abcf-5310661c74e7)

![IMG_20240102_210132.jpg](https://github.com/stantanasi/streamflix/assets/102837471/848ea98c-25a2-4e6e-8c82-1eca380185c5)

Please see this image for reference. 
The TV series image above are "Berlin" and "One Piece"

I usually encountered this when a New Series or movies came out. Also I think the app is not supported on my smart TV "Mi Tv Stick"cause its like a zoom a little bit. Thanks for the fast reply.

**Comment by Chardyyy07** [comment]
It's okay now I adjust the screen of my Tv Stick and the subtitles are properly aligned. I am an aspiring developer and I'm amazed by your work.

**Comment by stantanasi** [comment]
Okay great.
Thank you, that means a lot! ❤️
