### ISSUE TITLE
Provide support for Android smartphones

### ISSUE THREAD

**Issue by vivekch0976** [stantanasi/streamflix#6]
Hi, can you please provide support for android smartphones?  So that we can enjoy it on mobile phones as well.

**Comment by stantanasi** [comment]
I don't plan to support Android smartphones at this time. I still intend to make them compatible but only when the Android TV app is fully functional.

For now if you know how to use Android Studio, you could replace `true` by `false` on this line:
https://github.com/stantanasi/sflix/blob/e4bf1b0906137b36b2c02dfc18724a5f31f7c343/app/src/main/AndroidManifest.xml#L12
By setting `required="false"`, you will be able to launch the app on your Android smartphone.

But I have to warn you that the app is not optimized for small touchscreens, so you may have some difficulty navigating through movies and TV shows.

**Comment by stantanasi** [comment]
For now if you know how to use Android Studio, you could replace `true` by `false` on this line:
https://github.com/stantanasi/sflix/blob/e4bf1b0906137b36b2c02dfc18724a5f31f7c343/app/src/main/AndroidManifest.xml#L12
By setting `required="false"`, you will be able to launch the app on your Android smartphone.

But I have to warn you that the app is not optimized for small touchscreens, so you may have some difficulty navigating through movies and TV shows.

**Comment by Pluncidelst** [comment]
> Hi, can you please provide support for android smartphones? So that we can enjoy it on mobile phones as well.

If you go to sflix.to and scroll to the bottom, they offer an apk that has even more features than this app.

<img width="1428" alt="Screen Shot 2022-12-13 at 3 16 02 PM" src="https://user-images.githubusercontent.com/84115939/207456254-ed99c4bc-fd58-49ea-944b-da8ef4069a09.png">

**Comment by krysor** [comment]
> > Hi, can you please provide support for android smartphones? So that we can enjoy it on mobile phones as well.
> 
> If you go to sflix.to and scroll to the bottom, they offer an apk that has even more features than this app.
>

Is it open source tho?

**Comment by DarkCrypt** [comment]
@Pluncidelst 
> If you go to sflix.to and scroll to the bottom, they offer an apk that has even more features than this app.

This particular app is found in the footer of multiple sites similar to Sflix. It's called OnStream.
___
@krysor 
> Is it open source tho?

Definitely not. Open source is not stated anywhere.

**Comment by stantanasi** [comment]
Finally working on it 🥳

**Comment by stantanasi** [comment]
**Available on [Release 1.6.0](https://github.com/stantanasi/streamflix/releases/latest)**
