### ISSUE TITLE
Several QoL (Quality of Life) Improvement Requests

### ISSUE THREAD

**Issue by shadowscott** [stantanasi/streamflix#61]
### Summary

First off, amazing app. Just downloaded it to supplement other streaming apps that I have and it's very nice. Some qol feature requests that I was thinking about:

1. Resuming a video with different language/subtitle/provider/quality will retain previous values that were set. (i.e. setting subtitles for an anime, then backing out, then using the resume feature that's built in will retain the previous values set)
2. Mark episodes as "watched" so that when returning to a specific show/season you do not need to scroll through ALL episodes (most needed for Aniwatch since episodes are all under 1 season)
3. Not sure if this is a bug or Feature, but as indicated above some shows only display 1 season and all episodes are listed in it, specifically noticed this in Aniwatch shows. 
4. Ability to "clear" something from the Home page where it shows you progress of watched, just in case you start something and don't want to finish
5. Ability to favorite a show so we can go back to specific shows instead of needing to search again
6. 4k? Not sure if this is a limitation of the app or a limitation of the providers, but just wanted to ask since I don't see anything listed in the issues tab.

These are just some that I've thought of based on first impressions. I can try to think of more and add to this as an edit or as another comment, but let me know if this is not the right way to request these. Thanks again!

### Please confirm the following

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.

**Comment by stantanasi** [comment]
Great thank you for your message! Don't hesitate if you have other improvements.

> 1. Resuming a video with different language/subtitle/provider/quality will retain previous values that were set. (i.e. setting subtitles for an anime, then backing out, then using the resume feature that's built in will retain the previous values set)

Will do 🚀 

> 2. Mark episodes as "watched" so that when returning to a specific show/season you do not need to scroll through ALL episodes (most needed for Aniwatch since episodes are all under 1 season)

Will do 🚀 

> 3. Not sure if this is a bug or Feature, but as indicated above some shows only display 1 season and all episodes are listed in it, specifically noticed this in Aniwatch shows.

This is normal because the Aniwatch website has not implemented seasons, they have all the episodes in one place at the same time (but on a website it's more easy to navigate). Maybe I'll try to separate them like 1-100, 101-200 but it's more complicated than it seems.

> 4. Ability to "clear" something from the Home page where it shows you progress of watched, just in case you start something and don't want to finish

Will do 🚀 

> 5. Ability to favorite a show so we can go back to specific shows instead of needing to search again

Will do 🚀 

> 6. 4k? Not sure if this is a limitation of the app or a limitation of the providers, but just wanted to ask since I don't see anything listed in the issues tab.

Impossible for now because my app just retrieve movies/TV shows from streaming websites, if those websites don't have 2K or 4K available then I can't have them either.

**Comment by stantanasi** [comment]
For the issue of episodes, I was thinking of scrolling directly to last watched episodes or hiding watched episodes.
But changing the carousel to a list could also be a thing.

**Comment by oathzed** [comment]
> For the issue of episodes, I was thinking of scrolling directly to last watched episodes or hiding watched episodes. But changing the carousel to a list could also be a thing.

Skipping to last watched episode seems like the best option, I don't think hiding them is a good idea cause alot of people rewatch the same shows. Like the office, or friends etc. carousel is usually better for navigation on Android tv, unless you did something like Netflix? :o

**Comment by stantanasi** [comment]
> > For the issue of episodes, I was thinking of scrolling directly to last watched episodes or hiding watched episodes. But changing the carousel to a list could also be a thing.
> 
> Skipping to last watched episode seems like the best option, I don't think hiding them is a good idea cause alot of people rewatch the same shows. Like the office, or friends etc. carousel is usually better for navigation on Android tv, unless you did something like Netflix? :o

If I implement the hiding option, there would be a way to hide or show watched episodes, but for now I'm focalised on skipping them.
Also could you describe how it is on Netflix? I don't have Netflix myself

**Comment by shadowscott** [comment]
> > Skipping to last watched episode seems like the best option, I don't think hiding them is a good idea cause alot of people rewatch the same shows. Like the office, or friends etc. carousel is usually better for navigation on Android tv, unless you did something like Netflix? :o
> 
> 
> 
> If I implement the hiding option, there would be a way to hide or show watched episodes, but for now I'm focalised on skipping them.
> 
> Also could you describe how it is on Netflix? I don't have Netflix myself

Netflix does what you mentioned, skip to the end. That works too if it's easier than a toggle for hiding watched. The other app i mentioned does a hide which is fine. Either way I think as long as there's a way to bulk mark as watched (for instance "Mark all previous as watched" so you can do a bunch at once

**Comment by oathzed** [comment]
> > Skipping to last watched episode seems like the best option, I don't think hiding them is a good idea cause alot of people rewatch the same shows. Like the office, or friends etc. carousel is usually better for navigation on Android tv, unless you did something like Netflix? :o
> 
> If I implement the hiding option, there would be a way to hide or show watched episodes, but for now I'm focalised on skipping them. Also could you describe how it is on Netflix? I don't have Netflix myself

Makes sense.

Here is the title page: https://imgur.com/a/amAGy2t

And here is if you click to see more episodes:
https://imgur.com/a/0hzKbgZ

**Comment by stantanasi** [comment]
> 1. Resuming a video with different language/subtitle/provider/quality will retain previous values that were set. (i.e. setting subtitles for an anime, then backing out, then using the resume feature that's built in will retain the previous values set)
> 2. Mark episodes as "watched" so that when returning to a specific show/season you do not need to scroll through ALL episodes (most needed for Aniwatch since episodes are all under 1 season)
> 5. Ability to favorite a show so we can go back to specific shows instead of needing to search again

**Available on [Release 1.5.0](https://github.com/stantanasi/streamflix/releases/latest)**

> 4. Ability to "clear" something from the Home page where it shows you progress of watched, just in case you start something and don't want to finish

**Available on [Release 1.5.0](https://github.com/stantanasi/streamflix/releases/latest)**
You can remove a show in the "Continue watching" row by doing a long click on it.

**Comment by shadowscott** [comment]
Thanks for the updates. I do see the favorites and clear. Is there a way to mark a certain number of episodes watched, for instance I'm already halfway done with a show and want it to skip ahead. 

Also side note, trying to watch episodes on Aniwatch and getting bad-base64 error.

**Comment by stantanasi** [comment]
> Thanks for the updates. I do see the favorites and clear. Is there a way to mark a certain number of episodes watched, for instance I'm already halfway done with a show and want it to skip ahead.

Unfortunately, that feature isn't available yet.
However, for now, you can mark your previous episode as watched, by doing that the app will know your current episode.
For example, if you're at episode 50, you can watch episode 49, skip to the end to mark it as watched, then the app will propose you to watch episode 50 and scroll directly to it.

> Also side note, trying to watch episodes on Aniwatch and getting bad-base64 error.

Okay, I'll look into it. Maybe try again in a few hours; it might resolve itself.
