### ISSUE TITLE
Previous and next

### ISSUE THREAD

**Issue by Syhoto** [stantanasi/streamflix#62]
### Summary

Pls add previous and next feature like YouTube. And if possible the ability to save last used settings on next video or episode.

### Please confirm the following

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.

**Comment by stantanasi** [comment]
Completed in eafd9b1ce7dcbcb06268ca0ff10b478b17d87bce

**Comment by stantanasi** [comment]
**Available on [Release 1.5.0](https://github.com/stantanasi/streamflix/releases/latest)**
