### ISSUE TITLE
not working anymore 

### ISSUE THREAD

**Issue by geekyxpert** [stantanasi/streamflix#68]
### Description

everything loads but when trying to play anything you get Index:0 Size:0 error

### Reproduction steps

everything loads but when trying to play anything you get Index:0 Size:0 error

### App version

1.4.0

### Operating system

Fire tv os 8 , os 7 , Android tv , Google tv 12 

### Please confirm the following

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] If related to a provider, I have checked the site and it works, but not the app.

**Comment by stantanasi** [comment]
**Fixed on [Release 1.4.1](https://github.com/stantanasi/streamflix/releases/latest)**

**Comment by geekyxpert** [comment]
Thank you so much for your continuous support
