### ISSUE TITLE
Supporting a lower minsdk

### ISSUE THREAD

**Issue by raycekar** [stantanasi/streamflix#69]
### Summary

Would it be possible to support a lower minsdk than 23 or are there features needed for the app to run at 23?

I have a old fire tv stick that has fire os 5.2.9.5 (Lollipop sdk 22) and sadly that is the latest version it will ever get to.

If not, no worries as there are probably more important issues to address.

### Please confirm the following

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.

**Comment by oathzed** [comment]
It's time to update your device.. support a lower sdk only causes problems for new features

**Comment by stantanasi** [comment]
I will check if it's possible

**Comment by oathzed** [comment]
I take back what I said lol. Well partly, cause newer sdk still has better support for new features. Nice one Stan 🙏

**Comment by stantanasi** [comment]
**Available on [Release 1.5.0](https://github.com/stantanasi/streamflix/releases/latest)**

**Comment by stantanasi** [comment]
Also, I haven't had a chance to test it yet, so if you encounter any errors or odd displays, please feel free to let me know!
