### ISSUE TITLE
Have "watch S1 E1" always show

### ISSUE THREAD

**Issue by oathzed** [stantanasi/streamflix#70]
### Summary

When you open a new tv show, it should have the button "watch S1 E1" there already, so you don't have to click the season then the episode. Just simplifies things :)

### Please confirm the following

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.

**Comment by stantanasi** [comment]
**Available on [Release 1.5.1](https://github.com/stantanasi/streamflix/releases/latest)**
