### ISSUE TITLE
Add a view show, remove favourite button longpress

### ISSUE THREAD

**Issue by oathzed** [stantanasi/streamflix#71]
### Summary

When you're on the continue watching section, sometimes it's nice to be able to jump into a show to watch a different episode. So in the longpress put a button that says "view show", above the "remove" button.

Also add a long press to the favourites section, where you can quickly remove items from favourites.

### Please confirm the following

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.

**Comment by stantanasi** [comment]
**Available on [Release 1.5.1](https://github.com/stantanasi/streamflix/releases/latest)**
