### ISSUE TITLE
failed connect to aniwatch & sflix

### ISSUE THREAD

**Issue by wzben** [stantanasi/streamflix#75]
### Description

Message Error

"Failed to connect to aniwatch to/175.139.142.25 (port443)  from/172.20.0.3(port 51274) after 30000ms"

"Failed to connect to sflix to/175.139.142.25 (port443)  from/172.20.0.3(port 51274) after 30000ms"

### Reproduction steps

See Error

### App version

1.5.0

### Operating system

Android TV v10 | Kernel Version 4.9.180

### Please confirm the following

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] If related to a provider, I have checked the site and it works, but not the app.

**Comment by stantanasi** [comment]
This issue was closed because it has been stalled for too many days without activity. Please open a new issue if you believe you are encountering a related problem.
