### ISSUE TITLE
Ne fonctionne plus sur le lancement des videos

### ISSUE THREAD

**Issue by BaldLolo** [stantanasi/streamflix#79]
### Description

erreur HTTP 404 à chaque lancement de vidéo, sur aniwatch et sflix. Merci beaucoup pour cette super appli !!

### Reproduction steps

erreur HTTP 404 à chaque lancement de vidéo, sur aniwatch et sflix depuis le 28/02 à 16h.

### App version

1.5

### Operating system

google TV (android 12)

### Please confirm the following

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] If related to a provider, I have checked the site and it works, but not the app.

**Comment by stantanasi** [comment]
Ok je viens de voir, les serveurs ont probablement dû changer un truc dans leur code. Dès que je trouve la solution, je ferais une mise à jour !

**Comment by BaldLolo** [comment]
En tout cas merci beaucoup pour ton appli, c'est vraiment génial ce que tu fais ! Merci encore pour ton temps...

Envoyé à partir de Outlook pour Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by stantanasi** [comment]
Pour tenir au courant, j'ai pas réussi à résoudre l'erreur pour SFlix. Mais j'ai normalement corrigé HiAnime et AnyMovie qui semble fonctionner. En plus de ça, je suis actuellement entrain d'ajouter un nouveau provider qui devrait bien fonctionner

**Comment by BaldLolo** [comment]
Merci beaucoup pour l'info.

Envoyé à partir de Outlook pour Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by stantanasi** [comment]
**Je viens d'ajouter deux nouveaux providers (SoraStream et SuperStream) dans la [nouvelle version 1.6.1](https://github.com/stantanasi/streamflix/releases/latest)**
