### ISSUE TITLE
HTTP 404 error 

### ISSUE THREAD

**Issue by geekyxpert** [stantanasi/streamflix#80]
### Description

when you play any content you get HTTP 404 error 

### Reproduction steps

go to any movie or show and press watch now , error HTTP 404

### App version

1.5.0

### Operating system

android tv 11, google tv , fire tv , etc

### Please confirm the following

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] If related to a provider, I have checked the site and it works, but not the app.

**Comment by vi11ain** [comment]
Experience it too on my Google TV device

**Comment by stantanasi** [comment]
The videos servers have change their encryption method, as soon as I find a solution I will made a new release

**Comment by oathzed** [comment]
> The videos servers have change their encryption method, as soon as I find a solution I will made a new release

I think this is the importance of getting a provider like sorastream to work because there are so many providers in 1 that if 1 goes down there are still like 50 others, so you'll never not have stream links. Unfortunately sflix goes down a lot :(

**Comment by geekyxpert** [comment]
any update on this ?

**Comment by stantanasi** [comment]
I didn't manage to find a way to fixed SFlix videos decryption.
I made a new release where HiAnime (ex AniWatch) and AnyMovie seems to work. I'm currently working on implementing a new provider!

**Comment by stantanasi** [comment]
**Two new providers added (SoraStream and SuperStream) on [Release 1.6.1](https://github.com/stantanasi/streamflix/releases/latest)**

**Comment by stantanasi** [comment]
**SFlix and TMDb (ex SoraStream) fixed on [Release 1.6.5](https://github.com/stantanasi/streamflix/releases/latest)**
