### ISSUE TITLE
Trust anchor for certificate path not found.

### ISSUE THREAD

**Issue by wiredroid** [stantanasi/streamflix#82]
### Description

Exception while trying to watch a show.

### Reproduction steps

Select SFlix as provider.
Select video to watch
Select "Watch Now"

A toast notification pops up:

java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.

### App version

Latest

### Operating system

Google TV 12

### Logs

```bash
java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.
```

### Please confirm the following

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] If related to a provider, I have checked the site and it works, but not the app.

**Comment by stantanasi** [comment]
**Should be fixed on Release 1.6.12**
