### ISSUE TITLE
Aniwatch moved domain to hianime.to

### ISSUE THREAD

**Issue by xangelkawaiix** [stantanasi/streamflix#83]
### Summary

Title self explanatory, it gives error 521 on aniwatch because the domain has moved recently

### Please confirm the following

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.

**Comment by stantanasi** [comment]
Fixed on 5c60e5767f24c327d95dc89fb6ffac12e47c36ce

**Comment by stantanasi** [comment]
**Available on [Release 1.5.1](https://github.com/stantanasi/streamflix/releases/latest)**
