### ISSUE TITLE
New Release 1.5.1 still has a bug 

### ISSUE THREAD

**Issue by intellimediatv** [stantanasi/streamflix#84]
### Description

Upon trying to click "play" on any movie there is an error making any content unplayable image below
![20240309_095351](https://github.com/stantanasi/streamflix/assets/109838034/996a291d-e053-4a43-84e6-a047ae12d8e9)
![20240309_095351](https://github.com/stantanasi/streamflix/assets/109838034/07b92d48-8407-4295-9ef1-27f36afec228)

### Reproduction steps

Go to "play" or "watch" new bug screen shot attached unable to play content

### Operating system

Nvidia Shield Android TV OS version 11.0

### Please confirm the following

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] If related to a provider, I have checked the site and it works, but not the app.

**Comment by stantanasi** [comment]
Yeah I know, I didn't manage to find a way to fixed SFlix videos decryption.
But HiAnime (ex AniWatch) and AnyMovie seems to work. I'm currently working on implementing a new provider!

**Comment by intellimediatv** [comment]
Have you considered the provider sorastream?

**Comment by stantanasi** [comment]
Someone else told me about this one, I didn't have time to look into it
But because everyone talking about it, it should be probable that I will implement it

**Comment by oathzed** [comment]
> Someone else told me about this one, I didn't have time to look into it But because everyone talking about it, it should be probable that I will implement it

Yay! I'm excited for this one :D

**Comment by geekyxpert** [comment]
sorastream and https://www.braflix.video/ are so good check it out

**Comment by stantanasi** [comment]
**Two new providers added (SoraStream and SuperStream) on [Release 1.6.1](https://github.com/stantanasi/streamflix/releases/latest)**

**Comment by stantanasi** [comment]
**SFlix and TMDb (ex SoraStream) fixed on [Release 1.6.5](https://github.com/stantanasi/streamflix/releases/latest)**
