### ISSUE TITLE
Movies long press show "mark as watched"

### ISSUE THREAD

**Issue by oathzed** [stantanasi/streamflix#85]
![PXL_20240310_023939458 MP](https://github.com/stantanasi/streamflix/assets/52545913/fb14446c-8190-43a5-95ea-bd8ad48ca889)
### Description

I'm seeing that there is a "mark as watched" button added to the long press of movies? This is nice if you add a "History" section to the app, but right now it seems kind of useless :o.

Just wondering if that's where you're going with that

Cheers!

### Reproduction steps

1. Go to sflix
2. Long press on a movie 
3. See that it says "mark as watched"

### App version

Latest

### Operating system

Android 12

### Please confirm the following

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] If related to a provider, I have checked the site and it works, but not the app.

**Comment by intellimediatv** [comment]
This is not a bug but a feature implementation by the dev that is still not fully implemented into the app 100% as it relates to a history section as yet be patient
