### ISSUE TITLE
Creating multiple of the same show in continue watching

### ISSUE THREAD

**Issue by oathzed** [stantanasi/streamflix#87]
### Description

Right now when you watch an episode half way, it adds it to your continue watching section and that's good, now if you watch another episode half way it also adds it to you continue watching. So you'll have 2 results in your continue watching of the same show. This kind of clutters up the continue watching section.

What I'm proposing is, if I watch an episode half way that episode gets added to the continue watching, now if I watch another episode half way, it should replace that previous episode in the continue watching section. (Basically whatever your "Watch S#E#" says, that is what should be in your continue watching section. We shouldn't have duplicates of the same show)

### Reproduction steps

1. Go to any show
2.  Watch episode 1 half way, watch episode 2 half way
3. Go back to home, see that episode 1 and 2 are both in your continue watching.
4. What should actually happen is that only episode 2 is in the continue watching section 
5. It should take the data from your previously watched episode in the "Watch S#E#" button.

Obviously your watch progress of episode 1 being watched halfway will still be available for you to see, in the "seasons" tab

### App version

Latest

### Operating system

Android 12

### Please confirm the following

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] If related to a provider, I have checked the site and it works, but not the app.

**Comment by stantanasi** [comment]
I'm very hesitant about whether I should implement this functionality
I find it more pleasant to have all the episodes we started watching in "Watch next" but if you think it is better to have only one episode of each series then I will implement it!

**Comment by oathzed** [comment]
> I'm very hesitant about whether I should implement this functionality I find it more pleasant to have all the episodes we started watching in "Watch next" but if you think it is better to have only one episode of each series then I will implement it!

I just think it's better UX, it's how Netflix and the like do it. Basically just keep the play history for those episodes you partly watched but yeh whatever most recent episode you watched partly have it be on the continue watching section. Cause if I watched something part way and wanting to go to another episode I either didn't want to finish that previous episode, or it's a show that we rewatch all the time like "The Office" or "Friends" where you watch random episodes. It just seems like the continue watching section will get cluttered at that point and you'll have to remove stuff to keep it organized

**Comment by stantanasi** [comment]
Oh okay I see
Yes I will do that

**Comment by stantanasi** [comment]
**Available on Release 1.6.7**
