### ISSUE TITLE
Use the extension system

### ISSUE THREAD

**Issue by mizu-048** [stantanasi/streamflix#90]
### Summary

All the providers are already built-in inside the app which makes the app really easy to setup but it increases the chances of a DMCA strike like the one on cloudstream, so i recommend that you use the extension system or a similiar way to add functionality to the app.

### Please confirm the following

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.

**Comment by KillerDogeEmpire** [comment]
Man ripped sorastream from Cloudstream

**Comment by mizu-048** [comment]
now it just needs to release on PC and we're doomed

**Comment by DarkCrypt** [comment]
GitHub is a DMCA takedown goldmine. An extension system seems to be the only workaround. Personally, if I were building apps that could get taken down I'd self-host instead.

**Comment by DarkCrypt** [comment]
@KillerDogeEmpire, @IndusAryan
> Man ripped sorastream from Cloudstream

I know you 2 are CloudStream devs/contributors and it looks like you're not happy about this. Stantanasi is only fulfilling user requests like any good dev would.

Using SoraStream as a provider is an issue for you guys?

**Comment by DarkCrypt** [comment]
> now it just needs to release on PC and we're doomed

Nah, Android emulator on PC should suffice. I haven't tested that yet but I will now.

**Comment by mizu-048** [comment]
> @KillerDogeEmpire, @IndusAryan
> > Man ripped sorastream from Cloudstream
> 
> I know you 2 are CloudStream devs/contributors and it looks like you're not happy about this. Stantanasi is only fulfilling user requests like any good dev would.
> 
> Using SoraStream as a provider is an issue for you guys?

not at all(idk about others but atleast not me), the main devs planned to make the cloudstream api multi-platform themselves for some time so nothing to be angry about and its not like the devs make money off of cloudstream.

**Comment by mizu-048** [comment]
> > now it just needs to release on PC and we're doomed
> 
> Nah, Android emulator on PC should suffice. I haven't tested that yet but I will now.

an emulator is the problem, native support is what i am talking about. Emulators are slow, clunky and full of trackers. WSA is dead which we initially recommended to use.

**Comment by DarkCrypt** [comment]
> not at all(idk about others but atleast not me), the main devs planned to make the cloudstream api multi-platform themselves for some time so nothing to be angry about and its not like the devs make money off of cloudstream.

Ok, that's what I thought. I also thought SoraStream was open source so that's why I was curious. I would of been confused if this caused a conflict. There's more apps that would benefit using this provider but I wasn't sure if I should say anything.

**Comment by DarkCrypt** [comment]
> an emulator is the problem, native support is what i am talking about. Emulators are slow, clunky and full of trackers. WSA is dead which we initially recommended to use.

This is very true. I'm pissed off WSA is falling off the map, I really like it a lot.

**Comment by KillerDogeEmpire** [comment]
> > not at all(idk about others but atleast not me), the main devs planned to make the cloudstream api multi-platform themselves for some time so nothing to be angry about and its not like the devs make money off of cloudstream.
> 
> Ok, that's what I thought. I also thought SoraStream was open source so that's why I was curious. I would of been confused if this caused a conflict. There's more apps that would benefit using this provider but I wasn't sure if I should say anything.

@DarkCrypt 
I'm not really upset, just think that if many apps use it, the api's that it uses will notice and prevent it from working. Just think if people do use it they should hide the api's but they cam still be found with decompiler.

**Comment by DarkCrypt** [comment]
@KillerDogeEmpire 
I was hoping you'd reply, thank you for doing so. That clears it up for me and also makes sense. I don't want bad things to happen either. I'll keep this provider to myself for said reasons.

Just my opinion, between CloudStream and Streamflix, there's really no need to use other apps anyway. I really respect and appreciate all participating devs with both projects. God bless you all friends!

**Comment by mizu-048** [comment]
@DarkCrypt apps are bound to come and people will use them, just take music player or note taking apps for examples.

StreamFlix or cloudstream neither of them is perfect, an app offering even a single of those lacking feature would be used by someone for their needs, some examples would be PC support, chromecast, torrenting, built-in vpn(i bet you it will be a thing), better UI,etc etc

Most people will just use what they come across first and wouldn't make the effort to switch unless they are facing some issue.

**Comment by IndusAryan** [comment]
@DarkCrypt not problem, neither we are owners of sorastream, but i would suggest to use a different names for extensions if copied from cs3, like make sorastream -> turbostream, because this app comes with built in extensions.

**Comment by stantanasi** [comment]
Closing this issue because it's not possible to use the extension system in my app
