### ISSUE TITLE
"Watch" button not showing Season

### ISSUE THREAD

**Issue by oathzed** [stantanasi/streamflix#91]
### Description

Since the new 1.6.0 update, we no longer see the season number on the watch button

### Reproduction steps

1. go to a show
2. see it just says "E1" for instance

look at this video for reference, here it should say "S2E1" https://imgur.com/a/Muu3Uzm

### App version

1.6.0

### Operating system

shield android tv, android 11

### Please confirm the following

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] If related to a provider, I have checked the site and it works, but not the app.

**Comment by stantanasi** [comment]
My bad ^^

**Comment by oathzed** [comment]
> My bad ^^

no problem :) ty for the quick fix!

**Comment by oathzed** [comment]
> My bad ^^

Great Job on the new Sorastream provider man! looking forward when you add more extractors to it :).

This "Watch E1" bug seems to still persist in v1.6.1, only on certain shows though.
Recreate: use sora stream provider > go to show "Halo" > see result of "Watch E1".

I'm thinking it has something to do with "Specials" being added. If a show has specials, have it still start on S1E1 in the button

Cheers!

**Comment by oathzed** [comment]
> > My bad ^^
> 
> Great Job on the new Sorastream provider man! looking forward when you add more extractors to it :).
> 
> This "Watch E1" bug seems to still persist in v1.6.1, only on certain shows though. Recreate: use sora stream provider > go to show "Halo" > see result of "Watch E1".
> 
> I'm thinking it has something to do with "Specials" being added. If a show has specials, have it still start on S1E1 in the button
> 
> Cheers!

@stantanasi was this one fixed for next release? Or do you want me to create an new issue for it?
Thanks!❤️

**Comment by stantanasi** [comment]
No it's okay I will fix it now!

**Comment by oathzed** [comment]
> No it's okay I will fix it now!

Thank you!

**Comment by stantanasi** [comment]
**Fixed on [Release 1.6.3](https://github.com/stantanasi/streamflix/releases/latest)**
