### ISSUE TITLE
[Mobile bug] you can't swipe left or right on the top featured items

### ISSUE THREAD

**Issue by oathzed** [stantanasi/streamflix#95]
### Description

try swiping left or right on the top featured items, nothing happens

### Reproduction steps

video for reference: https://imgur.com/a/5S4YWhs

### App version

1.6.0

### Operating system

google pixel 7

### Please confirm the following

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] If related to a provider, I have checked the site and it works, but not the app.

**Comment by oathzed** [comment]
I just did some further testing with this, and it does look like you can swipe them left or right, but its super finicky. Maybe a small area triggers it by the title? would be nice if it was the whole tile

**Comment by stantanasi** [comment]
**Available on [Release 1.6.3](https://github.com/stantanasi/streamflix/releases/latest)**
