### ISSUE TITLE
[Mobile issue] Provider selector staying over top of titles

### ISSUE THREAD

**Issue by oathzed** [stantanasi/streamflix#96]
### Description

I know this might seem nice for quick access, but its a bit obtrusive, having it always over top of everything.
maybe it would be nicer, to just have it stay at the top, and when you scroll down it gets scrolled up and you don't see it.

i think this is the last issue I've found for the new mobile UI, so sorry for all the reports today, just want to help make the app awesome :D

### Reproduction steps

video for reference: https://imgur.com/a/Z1jVpfi

### App version

1.6.0

### Operating system

google pixel 7

### Please confirm the following

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] If related to a provider, I have checked the site and it works, but not the app.

**Comment by stantanasi** [comment]
Thanks, man, for pointing out all the issues. I'm already aware of most of them, but fixing them would have taken up a lot of time. I've decided to release the mobile app first and then address those issues. So, thanks again for bringing them up; it'll help me keep them in mind.

**Comment by oathzed** [comment]
> Thanks, man, for pointing out all the issues. I'm already aware of most of them, but fixing them would have taken up a lot of time. I've decided to release the mobile app first and then address those issues. So, thanks again for bringing them up; it'll help me keep them in mind.

Anytime man, glad I can help :). Thanks for your explanation ❤️

**Comment by stantanasi** [comment]
I think about this for a long time, but finally I will not implement it, because if the provider doesn't have a "Featured" list on top, it will not works or looks weird.

Example with SerienStream which doesn't have a Featured list on their website:

![Screenshot_20241014-192622_Streamflix - debug](https://github.com/user-attachments/assets/2d1ac269-a19a-4083-bed1-b0f2d59db995)

**Comment by oathzed** [comment]
> I think about this for a long time, but finally I will not implement it, because if the provider doesn't have a "Featured" list on top, it will not works or looks weird.
> 
> Example with SerienStream which doesn't have a Featured list on their website:
> 
> ![Screenshot_20241014-192622_Streamflix - debug](https://private-user-images.githubusercontent.com/46174829/376336716-2d1ac269-a19a-4083-bed1-b0f2d59db995.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg5Mjc0NDYsIm5iZiI6MTcyODkyNzE0NiwicGF0aCI6Ii80NjE3NDgyOS8zNzYzMzY3MTYtMmQxYWMyNjktYTE5YS00MDgzLWJlZDEtYjBmMmQ1OWRiOTk1LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDE0VDE3MzIyNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTlkYWQxN2UxYTkxY2Q0ZDMxNTc2ZTZmYmNlODYyZjIwNjdjZmVlMTc4NzVjNmJkY2JiYjg1YmFkZmZhNWFlMjcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.yZLXV2cjhaKvrojZ0Xw8r2DdMVOyLk-T3k6cVoJ8LPM)

Ahh ok, that makes sense. thanks for considering anyway 🙏
