### ISSUE TITLE
Phone / TV

### ISSUE THREAD

**Issue by DanRektLOL** [stantanasi/streamflix#97]
### Summary

 i have a really low quality tv box which runs android, so, when i install app on it, it runs like phone not tv. please workaround

### Please confirm the following

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.

**Comment by stantanasi** [comment]
Someone mentioned that during the first launch, it starts the mobile version (#92), but by closing and restarting the app, it resolves itself. Have you tried that?

**Comment by DanRektLOL** [comment]
yeah, my tv box is really low quality and it is recognized by every app as a phone except youtube (because there are 2 versions of yt, yt and yt for android tv)

**Comment by DanRektLOL** [comment]
so, basically please add some feature that allows the tv interface on phone or something like that i think

**Comment by oathzed** [comment]
> Can you try with the new version 1.6.1 if you still have this issue please

Maybe I'm wrong, but I'm not sure there is much you can do on your end. This guy has an Android device that says it's "tv device", but it's really just the android mobile OS. That's why it thinks he's using the phone. He would have to spoof it on his end likely in the build prop file.

Honestly he should just buy an actual android tv device they're like 20$ lol

**Comment by oathzed** [comment]
> > Can you try with the new version 1.6.1 if you still have this issue please
> 
> Maybe I'm wrong, but I'm not sure there is much you can do on your end (minus putting in a setting to force it, but that might complicate the UI xD) This guy has an Android device that says it's "tv device", but it's really just the android mobile OS. That's why it thinks he's using the phone. He would have to spoof it on his end likely in the build prop file.
> 
> Honestly he should just buy an actual android tv device they're like 20$ lol

**Comment by DanRektLOL** [comment]
> > Can you try with the new version 1.6.1 if you still have this issue please
> 
> Maybe I'm wrong, but I'm not sure there is much you can do on your end (minus putting in a setting to force it, but that might complicate the UI xD). This guy has an Android device that says it's "tv device", but it's really just the android mobile OS. That's why it thinks he's using the phone. He would have to spoof it on his end likely in the build prop file.
> 
> Honestly he should just buy an actual android tv device they're like 20$ lol

Yeah exactly, but just so you know, 20 dollars in my country 5 and a half thousand so, yeah. and im not saying its tv, im saying that my cheap tv box runs android and is actually a phone running some kind of launcher to make it a sort of tv. so my question is, is it possible to get the tv UI on phone?

**Comment by DarkCrypt** [comment]
> Yeah exactly, but just so you know, 20 dollars in my country is 5 and a half thousand. and im not saying its a tv, im saying that my cheap "tv" box runs android and is actually a phone running some kind of launcher to make it a sort of tv. so my question is, is it possible to get the tv UI on phone?

Damn, this is sad and painful. $20 is nothing in my country. How are you even getting this to work on your tv? An HDMI cord, screen mirror, or some other way?

> youtube (because there are 2 versions of yt, yt and yt for android tv)

This is also just as sad and painful. The official YouTube apps are ad infested garbage. There's much better alternatives.

**Comment by DanRektLOL** [comment]
> > Yeah exactly, but just so you know, 20 dollars in my country is 5 and a half thousand. and im not saying its a tv, im saying that my cheap "tv" box runs android and is actually a phone running some kind of launcher to make it a sort of tv. so my question is, is it possible to get the tv UI on phone?
> 
> Damn, this is sad and painful. $20 is nothing in my country. How are you even getting this to work on your tv? An HDMI cord, screen mirror, or some other way?
> 
> > youtube (because there are 2 versions of yt, yt and yt for android tv)
> 
> This is also just as sad and painful. The official YouTube apps are ad infested garbage. There's much better alternatives.

HDMI

**Comment by DanRektLOL** [comment]
> I created a special APK containing only the TV UI. You can locate it in the assets of [release 1.6.1](https://github.com/stantanasi/streamflix/releases/tag/v1.6.1), named **[streamflix-v1.6.2-tv.apk](https://github.com/stantanasi/streamflix/releases/download/v1.6.1/streamflix-v1.6.2-tv.apk)**. This is a temporary solution, but it allows you to have the new providers. Even though it's version 1.6.2, I can't include it in Release 1.6.2 because the default app's in-app updater won't function properly.

Thank you, I'll try with this

**Comment by stantanasi** [comment]
**Possibility to change app UI layout on [Release 1.6.4](https://github.com/stantanasi/streamflix/releases/latest)**
